/*
 * Copyright (C) 2015 Pivotal Software, Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.experimentdesigner.model;

import java.util.ArrayList;
import java.util.Arrays;
import static nl.mpi.tg.eg.experimentdesigner.model.FeatureType.*;

/**
 * @since Aug 18, 2015 4:16:06 PM (creation date)
 * @author Peter Withers <peter.withers@mpi.nl>
 */
public enum PresenterType {

    transmission(new FeatureType[]{
        versionData, stopAudioRecorder, startAudioRecorderTag,
        randomMsPause, evaluatePause, addTimerTrigger, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching, countdownLabel, stimulusPresent,
        prevStimulusButton,
        prevStimulus, timerLabel, startTimer, habituationParadigmListener, triggerRandom, resetTrigger, clearTimer,
        logTimerValue,
        //        logTokenText, 
        actionTokenButton,
        clearPage,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        showStimuliReport,
        sendStimuliReport, requestNotification,
        //        hasMetadataValue,
        //        setMetadataValue, 
        //        setMetadataEvalTokens, 
        matchOnEvalTokens, progressIndicator,
        //        htmlTokenText, 
        stimulusButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputCapture, captureStart, touchEnd,
        clearCurrentScore,
        resetStimulus,
        playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        cancelPauseTimers, activateRandomItem, withStimuli, eachStimulus, groupStimuli,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton,
        //        switchUserIdButton, 
        selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton,
        showCurrentMs,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        //        popupMessage,
        stimulusAudio,
        stimulusImage,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        audioButton,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        showStimulusGrid, matchingStimulusGrid,
        showStimulus,
        startFrameRateTimer,
        //        pause,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        responseCorrect,
        responseIncorrect,
        hasMoreStimulus,
        endOfStimulus,
        multipleUsers, singleUser,
        userInfo,
        menuItem
    }),
    metadata(new FeatureType[]{
        stimulusPresent, stopAudioRecorder, startAudioRecorderTag,
        clearPage, activateRandomItem,
        randomMsPause, evaluatePause, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching,
        countdownLabel, playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp, versionData,
        clearCurrentScore,
        resetStimulus,
        touchInputCapture, captureStart, touchEnd,
        displayCompletionCode,
        sendMetadata,
        prevStimulusButton,
        prevStimulus, habituationParadigmListener, triggerRandom, resetTrigger, logTokenText,
        //        actionTokenButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, 
        stimulusButton,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        showStimuliReport,
        //        requestNotification,
        //        hasMetadataValue, setMetadataValue,
        //        setMetadataEvalTokens,
        //        matchOnEvalTokens, 
        //        progressIndicator,
        //        htmlTokenText, 
        sendStimuliReport,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        withStimuli, eachStimulus, groupStimuli,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        eraseLocalStorageButton, eraseUsersDataButton,
        showCurrentMs,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        validateMetadata, transmitResults, generateCompletionCode,
        // redirectToUrl, 
        sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        audioButton,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        stimulusImage,
        stimulusAudio,
        //        popupMessage,
        responseCorrect,
        responseIncorrect,
        hasMoreStimulus,
        endOfStimulus,
        userInfo,
        menuItem,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb,
        //        targetFooterButton, actionFooterButton
    }),
    preload(new FeatureType[]{
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection, logTokenText, actionTokenButton, habituationParadigmListener, triggerRandom, resetTrigger, addMediaTrigger,
        versionData, stopAudioRecorder, startAudioRecorderTag, addRecorderDtmfTrigger, addRecorderLevelTrigger,endAudioRecorderTag,
        withStimuli, eachStimulus, groupStimuli,
        activateRandomItem,
        displayCompletionCode, sendMetadata,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        //aboveThreshold,
        //        withinThreshold,
        withMatchingStimulus,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        allMenuItems,
        nextStimulusButton,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        audioButton,
        userInfo,
        menuItem,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        //        onError,
        //        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        startFrameRateTimer,
        //        popupMessage,
        pause,
        doLater,
        zeroStimulusStopwatch, stopStimulusStopwatch, responseCorrect, responseIncorrect, hasMoreStimulus, endOfStimulus}),
    stimulus(new FeatureType[]{
        preloadAllStimuli,
        showColourReport,
        activateRandomItem,
        displayCompletionCode, sendMetadata,
        versionData,
        submitTestResults,
        helpDialogue,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        userInfo,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        allMenuItems,
        menuItem,
        addKinTypeGui,
        //        onError,
        //        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        preloadAllStimuli}),
    colourPicker(new FeatureType[]{
        regionAppend, stopAudioRecorder,
        regionClear,
        regionReplace,
        regionStyle,
        regionCodeStyle,
        gotoPresenter,
        svgLoadGroups, svgGroupAdd, svgSetLabel, svgGroupShow, svgGroupAction, svgGroupMatching,
        gotoNextPresenter,
        timerLabel, startTimer, clearTimer, logTimerValue, logTokenText, actionTokenButton, compareTimer, habituationParadigmListener, triggerRandom, resetTrigger,
        row, plainText, stimulusPresent,
        countdownLabel, triggerMatching, table, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,touchInputCapture, captureStart, touchEnd, column,
        stimulusMetadataField,
        requestNotification, hasMetadataValue, setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, progressIndicator,
        //        htmlTokenText,
        evaluateTokenText,
        showStimuliReport,
        sendStimuliReport,
        stimulusButton, touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputStop,
        stimulusHasResponse, cancelPauseTimers,
        displayCompletionCode,
        sendMetadata, prevStimulusButton,
        prevStimulus,
        hasGetParameter, activateRandomItem, showHtmlPopup,
        randomMsPause, evaluatePause, addTimerTrigger, playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        //        helpDialogue,
        clearCurrentScore,
        resetStimulus,
        showColourReport,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        aboveThreshold,
        withinThreshold, withStimuli, eachStimulus, groupStimuli,
        submitTestResults,
        image, timerLabel, htmlText, plainText,
        actionFooterButton,
        //        actionButton, 
        hotKeyInput, targetButton, targetFooterButton, addPadding, centrePage, clearPage,
        startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, stopAudioRecorder, startAudioRecorderTag, endAudioRecorderTag,
        loadKinTypeStringDiagram, localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        //        loadStimulus, 
        clearStimulusResponses, loadSdCardStimulus,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        versionData,
        eraseLocalStorageButton, eraseUsersDataButton,
        enableButtonGroup,
        disableButtonGroup,
        showStimulusProgress, stimulusFreeText, backgroundImage, stimulusImageCapture,
        hideButtonGroup,
        styleButtonGroup,
        showButtonGroup, requestFocus,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton, stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        responseCorrect,
        responseIncorrect,
        //        hasMoreStimulus,
        //        endOfStimulus,
        showCurrentMs,
        audioButton,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        startFrameRateTimer,
        pause,
        doLater,
        //        popupMessage,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        onError,
        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        stimulusImage,
        stimulusAudio,
        userInfo,
        zeroStimulusStopwatch, stopStimulusStopwatch, menuItem}),
    colourReport(new FeatureType[]{
        timerLabel, startTimer, clearTimer, logTimerValue, logTokenText, actionTokenButton, compareTimer, habituationParadigmListener, triggerRandom, resetTrigger,
        activateRandomItem, stopAudioRecorder, startAudioRecorderTag,
        //        versionData,
        randomMsPause, evaluatePause, addTimerTrigger, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching,
        countdownLabel,
        stimulusPresent, clearCurrentScore,
        prevStimulusButton,
        prevStimulus,
        clearPage,
        resetStimulus,
        playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        cancelPauseTimers, validateMetadata, transmitResults, generateCompletionCode, withStimuli, eachStimulus, groupStimuli,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        displayCompletionCode,
        sendMetadata,
        showStimuliReport,
        sendStimuliReport, requestNotification,
        //        hasMetadataValue, 
        setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens,
        //progressIndicator, 
        //        htmlTokenText, 
        stimulusButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputCapture, captureStart, touchEnd,
        touchInputStop,
        stimulusHasResponse,
        helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        //        aboveThreshold,
        //        withinThreshold,
        loadKinTypeStringDiagram, localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        showStimulusProgress, stimulusFreeText, backgroundImage, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb,
        //        targetFooterButton, actionFooterButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        responseCorrect,
        responseIncorrect,
        hasMoreStimulus,
        endOfStimulus,
        showCurrentMs,
        audioButton,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        startFrameRateTimer,
        pause,
        doLater,
        //        popupMessage,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        //        onError,
        //        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        stimulusImage,
        stimulusAudio,
        userInfo,
        menuItem}),
    kindiagram(new FeatureType[]{
        activateRandomItem, stopAudioRecorder, startAudioRecorderTag,
        versionData,
        randomMsPause, evaluatePause, addTimerTrigger, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching, countdownLabel, stimulusPresent, clearCurrentScore,
        prevStimulusButton,
        prevStimulus, timerLabel, startTimer, compareTimer, habituationParadigmListener, triggerRandom, resetTrigger, clearTimer, logTimerValue, logTokenText, actionTokenButton,
        clearPage,
        resetStimulus,
        playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        cancelPauseTimers, validateMetadata, transmitResults, generateCompletionCode, withStimuli, eachStimulus, groupStimuli,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        displayCompletionCode,
        sendMetadata,
        showStimuliReport,
        evaluateTokenText,
        sendStimuliReport, requestNotification, hasMetadataValue, setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, progressIndicator, htmlTokenText, stimulusButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputCapture, captureStart, touchEnd,
        touchInputStop,
        stimulusHasResponse,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        aboveThreshold,
        withinThreshold,
        responseCorrect, responseIncorrect, hasMoreStimulus, endOfStimulus,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        //        popupMessage,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        showCurrentMs,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        menuItem,
        AnnotationTimelinePanel, VideoPanel,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        audioButton,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        startFrameRateTimer,
        pause,
        doLater,
        onError,
        onSuccess,
        multipleUsers, singleUser,
        userInfo,
        stimulusImage,
        stimulusAudio
    }),
    menu(new FeatureType[]{
        versionData, stopAudioRecorder, startAudioRecorderTag,
        randomMsPause, evaluatePause, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching, countdownLabel, stimulusPresent, clearCurrentScore,
        prevStimulusButton,
        prevStimulus, habituationParadigmListener, triggerRandom, resetTrigger, logTokenText, actionTokenButton,
        clearPage,
        resetStimulus,
        playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        validateMetadata, transmitResults, generateCompletionCode, withStimuli, eachStimulus, groupStimuli,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        displayCompletionCode,
        sendMetadata,
        showStimuliReport,
        sendStimuliReport, requestNotification,
        //        hasMetadataValue, setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, 
        progressIndicator, // htmlTokenText, 
        stimulusButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputCapture, captureStart, touchEnd,
        touchInputStop,
        stimulusHasResponse,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        responseCorrect, responseIncorrect, hasMoreStimulus, endOfStimulus,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        //        popupMessage,
        localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        showCurrentMs,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        audioButton,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        //        onError,
        //        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        userInfo,
        stimulusImage,
        stimulusAudio}),
    debug(new FeatureType[]{
        activateRandomItem, stopAudioRecorder, startAudioRecorderTag,
        randomMsPause, evaluatePause, addTimerTrigger, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching, countdownLabel, stimulusPresent, clearCurrentScore,
        prevStimulusButton,
        prevStimulus, timerLabel, startTimer, compareTimer, habituationParadigmListener, triggerRandom, resetTrigger, clearTimer, logTimerValue, logTokenText, actionTokenButton,
        clearPage,
        resetStimulus,
        playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        touchInputStop,
        stimulusHasResponse,
        stimulusMetadataField,
        cancelPauseTimers, validateMetadata, transmitResults, generateCompletionCode, withStimuli, eachStimulus, groupStimuli,
        sendGroupStoredMessage, streamGroupCanvas, streamGroupCamera, sendGroupTokenMessage,
        displayCompletionCode,
        sendMetadata,
        showStimuliReport,
        evaluateTokenText,
        sendStimuliReport, requestNotification, hasMetadataValue, setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, progressIndicator, htmlTokenText, stimulusButton,
        touchInputLabelButton, touchInputImageButton, touchInputVideoButton, touchInputCapture, captureStart, touchEnd,
        touchInputStop,
        stimulusHasResponse,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        aboveThreshold,
        withinThreshold,
        responseCorrect, responseIncorrect, hasMoreStimulus, endOfStimulus,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        //        popupMessage,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        showCurrentMs,
        showStimulusProgress, stimulusFreeText, backgroundImage, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData, eraseUsersDataButton,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        menuItem,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        audioButton,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        startFrameRateTimer,
        pause,
        doLater,
        onError,
        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        loadKinTypeStringDiagram,
        stimulusImage,
        userInfo,
        stimulusAudio}),
    text(new FeatureType[]{
        requestNotification, stopAudioRecorder, startAudioRecorderTag,
        //        hasMetadataValue, 
        //        setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, 
        progressIndicator,
        //        htmlTokenText,
        versionData,
        randomMsPause, evaluatePause, addTimerTrigger, triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,triggerMatching, stimulusButton, logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection, touchInputLabelButton, touchInputImageButton, touchInputVideoButton, activateRandomItem, countdownLabel, stimulusPresent, playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp,
        clearCurrentScore,
        resetStimulus,
        clearPage, showStimuliReport,
        sendStimuliReport, logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection, touchInputCapture, captureStart, touchEnd, touchInputStop,
        stimulusHasResponse, stimulusMetadataField,
        cancelPauseTimers,
        displayCompletionCode,
        sendMetadata, prevStimulusButton,
        prevStimulus, timerLabel, startTimer, habituationParadigmListener, triggerRandom, resetTrigger, clearTimer, logTimerValue, logTokenText, actionTokenButton,
        //        hasGetParameter,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        loadKinTypeStringDiagram, localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        loadStimulus, clearStimulusResponses, loadSdCardStimulus,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        withStimuli, eachStimulus, groupStimuli,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause,
        stimulusLabel,
        responseCorrect,
        responseIncorrect,
        hasMoreStimulus,
        endOfStimulus,
        showCurrentMs,
        audioButton,
        showStimulus,
        showStimulusGrid, matchingStimulusGrid,
        pause,
        doLater,
        startFrameRateTimer,
        //        popupMessage,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        //        onError,
        //        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        AnnotationTimelinePanel, VideoPanel,
        stimulusImage,
        stimulusAudio,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        userInfo,
        menuItem
    }
    ),
    timeline(new FeatureType[]{
        sendStimuliReport, stopAudioRecorder, startAudioRecorderTag,
        activateRandomItem,
        triggerDefinition, addMediaTrigger, addRecorderDtmfTrigger, addRecorderLevelTrigger,randomMsPause, evaluatePause, addTimerTrigger, triggerMatching,
        countdownLabel, stimulusPresent, playMedia,
        rewindMedia,
        pauseMedia, logMediaTimeStamp, versionData,
        clearCurrentScore,
        resetStimulus,
        clearPage,
        prevStimulusButton,
        evaluateTokenText,
        requestNotification, hasMetadataValue, setMetadataValue, setMetadataEvalTokens, matchOnEvalTokens, progressIndicator, htmlTokenText, logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection, showStimuliReport, stimulusButton, touchInputLabelButton, touchInputImageButton, touchInputVideoButton, sendMetadata, prevStimulus,
        timerLabel, startTimer, compareTimer, habituationParadigmListener, triggerRandom, resetTrigger, clearTimer, logTimerValue, logTokenText, actionTokenButton,
        stimulusMetadataField,
        cancelPauseTimers,
        displayCompletionCode,
        stimulusHasResponse, touchInputStop, logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection, touchInputCapture, captureStart, touchEnd,
        showColourReport, submitTestResults, helpDialogue,
        submitGroupEvent, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel, groupMessageLabel, groupResponseStimulusImage,
        groupResponseFeedback, groupScoreLabel, groupChannelScoreLabel, groupMemberActivity, groupNetwork, groupMemberCodeLabel, groupMemberLabel,
        groupMessageLabel, groupResponseStimulusImage, groupResponseFeedback, scoreLabel, scoreIncrement, scoreAboveThreshold, bestScoreAboveThreshold, totalScoreAboveThreshold,
        aboveThreshold,
        withinThreshold,
        loadKinTypeStringDiagram, localStorageData, stimuliValidation, addKeyboardDebug, addDebugWidgets,
        //        loadStimulus, 
        clearStimulusResponses, loadSdCardStimulus,
        allMetadataFields, metadataFieldConnection, metadataField, metadataFieldVisibilityDependant, metadataFieldDateTriggered, saveMetadataButton, createUserButton, switchUserIdButton, selectUserMenu, selectLocaleMenu,
        existingUserCheck,
        eraseLocalStorageButton, eraseUsersDataButton,
        showStimulusProgress, stimulusFreeText, stimulusImageCapture,
        ratingFooterButton, ratingButton, ratingRadioButton, ratingCheckbox, stimulusRatingButton, stimulusRatingRadio, stimulusRatingCheckbox,
        zeroStimulusStopwatch, stopStimulusStopwatch, endAudioRecorderTag, startAudioRecorderApp, startAudioRecorderWeb, audioInputSelectWeb, targetFooterButton, actionFooterButton,
        validateMetadata, transmitResults, generateCompletionCode,
        redirectToUrl, sendAllData,
        eraseLocalStorageOnWindowClosing,
        //        clearStimulus,
        /*removeStimulus,*/ removeMatchingStimulus, withMatchingStimulus, nextMatchingStimulus,
        keepStimulus,
        nextStimulus,
        allMenuItems,
        nextStimulusButton,
        stimulusCodeImage, stimulusCodeAudio, stimulusCodeVideo,
        currentStimulusHasTag, sendGroupMessageButton, sendGroupMessage, stimulusHasRatingOptions,
        //        autoNextStimulus,
        addKinTypeGui,
        preloadAllStimuli,
        cancelPauseAll, stimulusPause, withStimuli, eachStimulus, groupStimuli,
        stimulusLabel,
        responseCorrect,
        responseIncorrect,
        //        hasMoreStimulus,
        //        endOfStimulus,
        showCurrentMs,
        audioButton,
        showStimulusGrid, matchingStimulusGrid,
        showStimulus,
        pause,
        doLater,
        startFrameRateTimer,
        //        popupMessage,
        logTimeStamp, hardwareTimeStamp, dtmfTone, recorderToneInjection,
        onError,
        onSuccess,
        multipleUsers, singleUser,
        kinTypeStringDiagram, editableKinEntitesDiagram,
        stimulusImage,
        stimulusAudio,
        userInfo,
        menuItem});

    private final FeatureType[] featureTypes;
    private final FeatureType[] excludedFeatureTypes;

    private PresenterType(FeatureType[] excludedFeatureTypes) {
        ArrayList<FeatureType> features = new ArrayList<>();
        features.addAll(Arrays.asList(FeatureType.values()));
        for (FeatureType excludedFeature : excludedFeatureTypes) {
            features.remove(excludedFeature);
        }
        this.excludedFeatureTypes = excludedFeatureTypes;
        this.featureTypes = features.toArray(new FeatureType[features.size()]);
    }

    public FeatureType[] getFeatureTypes() {
        return featureTypes;
    }

    public FeatureType[] getExcludedFeatureTypes() {
        return excludedFeatureTypes;
    }
}
