/*
 * Copyright (C) 2016 Max Planck Institute for Psycholinguistics
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.experimentdesigner.util;

import nl.mpi.tg.eg.experimentdesigner.controller.WizardController;
import nl.mpi.tg.eg.experimentdesigner.model.Experiment;
import nl.mpi.tg.eg.experimentdesigner.model.WizardData;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardAboutScreen;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardAgreementScreen;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardCompletionScreen;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardEditUserScreen;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardMenuScreen;
import nl.mpi.tg.eg.experimentdesigner.model.wizard.WizardMultiParticipantScreen;

/**
 * @since Oct 21, 2016 11:52:03 AM (creation date)
 * @author Peter Withers <peter.withers@mpi.nl>
 */
public class MultiParticipant {

    private final WizardController wizardController = new WizardController();
    // @todo: scoring for each participant 
    // @todo: the allocated member id must maintained thoughout the experiment
    // @todo: show the experiment total score not the participants score
    // @todo: round 0 is the naming screen and does not collect guesses and therefore no scores
    // @todo: make the stimuli list common between all group members
    //  @todo: limit the communication to within each channel
    // @todo: add the group data collection
    // @todo: add the group data CSV output
    // @todo: add an option in the admin reporting app to "hide ugly details" which hides strings like UUID and browser version strings

//,Round,Dyad,Game.no,Item.ID,Shape,Size,RawSize,ItemCurrentAge,Producer,Word,ACC
//165,1,AB,1,10,2,small,2.74,2,A,flup,0
//167,1,CD,1,10,2,small,2.74,2,C,mozel,1
//65,1,AB,2,5,1,small,2.94,2,B,mozel,1
//67,1,CD,2,5,1,small,2.94,2,D,tjalp,1
//297,1,AB,3,19,4,medium,4.4,2,A,flolp,1
//299,1,CD,3,19,4,medium,3.95,2,C,vlolp,1
//147,1,AB,4,9,2,medium,4.51,2,B,kimi,0
//149,1,CD,4,9,2,medium,4.51,2,D,vlalp,0
//85,1,AB,5,6,2,big,7.6,2,A,dauft,0
//87,1,CD,5,6,2,big,7.6,2,C,potmik,1
//    int[] possibleAngles = new int[]{30, 45, 60, 90, 120, 135, 150, 180, 210, 225, 240, 270, 300, 315, 330, 360};   
//    private String[] getStimuli(){
//        for (int textureIndex = 1; textureIndex < 29; textureIndex++) {
//            
//        }
//    }
    private final String[] stimuliArray = new String[]{
        //        "1.png:shape1:version1:moveRotated15",
        //        "2.png:shape1:version1:version1zero:moveRotated15",
        //        "3.png:shape1:version1:version1zero:version2:moveRotated15",
        //        "4.png:shape1:version3:version3zero:moveRotated15",
        "1.png:shape1:moveRotated15",
        "2.png:shape1:moveRotated15",
        "3.png:shape1:moveRotated15",
        "4.png:shape1:moveRotated15",
        "5.png:shape1:moveRotated15",
        "6.png:shape1:moveRotated15",
        "7.png:shape1:moveRotated15",
        "8.png:shape2:moveRotated15",
        "9.png:shape2:moveRotated15",
        "10.png:shape2:moveRotated15",
        "11.png:shape2:moveRotated15",
        "12.png:shape2:moveRotated15",
        "13.png:shape2:moveRotated15",
        "14.png:shape2:moveRotated15",
        "15.png:shape3:moveRotated15",
        "16.png:shape3:moveRotated15",
        "17.png:shape3:moveRotated15",
        "18.png:shape3:moveRotated15",
        "19.png:shape3:moveRotated15",
        "20.png:shape3:moveRotated15",
        "21.png:shape3:moveRotated15",
        "22.png:shape4:moveRotated15",
        "23.png:shape4:moveRotated15",
        "24.png:shape4:moveRotated15",
        "25.png:shape4:moveRotated15",
        "26.png:shape4:moveRotated15",
        "27.png:shape4:moveRotated15",
        "28.png:shape4:moveRotated15",
        "1.png:shape1:moveRotated30",
        "2.png:shape1:moveRotated30",
        "3.png:shape1:moveRotated30",
        "4.png:shape1:moveRotated30",
        "5.png:shape1:moveRotated30",
        "6.png:shape1:moveRotated30",
        "7.png:shape1:moveRotated30",
        "8.png:shape2:moveRotated30",
        "9.png:shape2:moveRotated30",
        "10.png:shape2:moveRotated30",
        "11.png:shape2:moveRotated30",
        "12.png:shape2:moveRotated30",
        "13.png:shape2:moveRotated30",
        "14.png:shape2:moveRotated30",
        "15.png:shape3:moveRotated30",
        "16.png:shape3:moveRotated30",
        "17.png:shape3:moveRotated30",
        "18.png:shape3:moveRotated30",
        "19.png:shape3:moveRotated30",
        "20.png:shape3:moveRotated30",
        "21.png:shape3:moveRotated30",
        "22.png:shape4:moveRotated30",
        "23.png:shape4:moveRotated30",
        "24.png:shape4:moveRotated30",
        "25.png:shape4:moveRotated30",
        "26.png:shape4:moveRotated30",
        "27.png:shape4:moveRotated30",
        "28.png:shape4:moveRotated30",
        "1.png:shape1:moveRotated45",
        "2.png:shape1:moveRotated45",
        "3.png:shape1:moveRotated45",
        "4.png:shape1:moveRotated45",
        "5.png:shape1:moveRotated45",
        "6.png:shape1:moveRotated45",
        "7.png:shape1:moveRotated45",
        "8.png:shape2:moveRotated45",
        "9.png:shape2:moveRotated45",
        "10.png:shape2:moveRotated45",
        "11.png:shape2:moveRotated45",
        "12.png:shape2:moveRotated45",
        "13.png:shape2:moveRotated45",
        "14.png:shape2:moveRotated45",
        "15.png:shape3:moveRotated45",
        "16.png:shape3:moveRotated45",
        "17.png:shape3:moveRotated45",
        "18.png:shape3:moveRotated45",
        "19.png:shape3:moveRotated45",
        "20.png:shape3:moveRotated45",
        "21.png:shape3:moveRotated45",
        "22.png:shape4:moveRotated45",
        "23.png:shape4:moveRotated45",
        "24.png:shape4:moveRotated45",
        "25.png:shape4:moveRotated45",
        "26.png:shape4:moveRotated45",
        "27.png:shape4:moveRotated45",
        "28.png:shape4:moveRotated45",
        "1.png:shape1:moveRotated60",
        "2.png:shape1:moveRotated60",
        "3.png:shape1:moveRotated60",
        "4.png:shape1:moveRotated60",
        "5.png:shape1:moveRotated60",
        "6.png:shape1:moveRotated60",
        "7.png:shape1:moveRotated60",
        "8.png:shape2:moveRotated60",
        "9.png:shape2:moveRotated60",
        "10.png:shape2:moveRotated60",
        "11.png:shape2:moveRotated60",
        "12.png:shape2:moveRotated60",
        "13.png:shape2:moveRotated60",
        "14.png:shape2:moveRotated60",
        "15.png:shape3:moveRotated60",
        "16.png:shape3:moveRotated60",
        "17.png:shape3:moveRotated60",
        "18.png:shape3:moveRotated60",
        "19.png:shape3:moveRotated60",
        "20.png:shape3:moveRotated60",
        "21.png:shape3:moveRotated60",
        "22.png:shape4:moveRotated60",
        "23.png:shape4:moveRotated60",
        "24.png:shape4:moveRotated60",
        "25.png:shape4:moveRotated60",
        "26.png:shape4:moveRotated60",
        "27.png:shape4:moveRotated60",
        "28.png:shape4:moveRotated60",
        "1.png:shape1:moveRotated75",
        "2.png:shape1:moveRotated75",
        "3.png:shape1:moveRotated75",
        "4.png:shape1:moveRotated75",
        "5.png:shape1:moveRotated75",
        "6.png:shape1:moveRotated75",
        "7.png:shape1:moveRotated75",
        "8.png:shape2:moveRotated75",
        "9.png:shape2:moveRotated75",
        "10.png:shape2:moveRotated75",
        "11.png:shape2:moveRotated75",
        "12.png:shape2:moveRotated75",
        "13.png:shape2:moveRotated75",
        "14.png:shape2:moveRotated75",
        "15.png:shape3:moveRotated75",
        "16.png:shape3:moveRotated75",
        "17.png:shape3:moveRotated75",
        "18.png:shape3:moveRotated75",
        "19.png:shape3:moveRotated75",
        "20.png:shape3:moveRotated75",
        "21.png:shape3:moveRotated75",
        "22.png:shape4:moveRotated75",
        "23.png:shape4:moveRotated75",
        "24.png:shape4:moveRotated75",
        "25.png:shape4:moveRotated75",
        "26.png:shape4:moveRotated75",
        "27.png:shape4:moveRotated75",
        "28.png:shape4:moveRotated75",
        "1.png:shape1:moveRotated90",
        "2.png:shape1:moveRotated90",
        "3.png:shape1:moveRotated90",
        "4.png:shape1:moveRotated90",
        "5.png:shape1:moveRotated90",
        "6.png:shape1:moveRotated90",
        "7.png:shape1:moveRotated90",
        "8.png:shape2:moveRotated90",
        "9.png:shape2:moveRotated90",
        "10.png:shape2:moveRotated90",
        "11.png:shape2:moveRotated90",
        "12.png:shape2:moveRotated90",
        "13.png:shape2:moveRotated90",
        "14.png:shape2:moveRotated90",
        "15.png:shape3:moveRotated90",
        "16.png:shape3:moveRotated90",
        "17.png:shape3:moveRotated90",
        "18.png:shape3:moveRotated90",
        "19.png:shape3:moveRotated90",
        "20.png:shape3:moveRotated90",
        "21.png:shape3:moveRotated90",
        "22.png:shape4:moveRotated90",
        "23.png:shape4:moveRotated90",
        "24.png:shape4:moveRotated90",
        "25.png:shape4:moveRotated90",
        "26.png:shape4:moveRotated90",
        "27.png:shape4:moveRotated90",
        "28.png:shape4:moveRotated90",
        "1.png:shape1:moveRotated105",
        "2.png:shape1:moveRotated105",
        "3.png:shape1:moveRotated105",
        "4.png:shape1:moveRotated105",
        "5.png:shape1:moveRotated105",
        "6.png:shape1:moveRotated105",
        "7.png:shape1:moveRotated105",
        "8.png:shape2:moveRotated105",
        "9.png:shape2:moveRotated105",
        "10.png:shape2:moveRotated105",
        "11.png:shape2:moveRotated105",
        "12.png:shape2:moveRotated105",
        "13.png:shape2:moveRotated105",
        "14.png:shape2:moveRotated105",
        "15.png:shape3:moveRotated105",
        "16.png:shape3:moveRotated105",
        "17.png:shape3:moveRotated105",
        "18.png:shape3:moveRotated105",
        "19.png:shape3:moveRotated105",
        "20.png:shape3:moveRotated105",
        "21.png:shape3:moveRotated105",
        "22.png:shape4:moveRotated105",
        "23.png:shape4:moveRotated105",
        "24.png:shape4:moveRotated105",
        "25.png:shape4:moveRotated105",
        "26.png:shape4:moveRotated105",
        "27.png:shape4:moveRotated105",
        "28.png:shape4:moveRotated105",
        "1.png:shape1:moveRotated120",
        "2.png:shape1:moveRotated120",
        "3.png:shape1:moveRotated120",
        "4.png:shape1:moveRotated120",
        "5.png:shape1:moveRotated120",
        "6.png:shape1:moveRotated120",
        "7.png:shape1:moveRotated120",
        "8.png:shape2:moveRotated120",
        "9.png:shape2:moveRotated120",
        "10.png:shape2:moveRotated120",
        "11.png:shape2:moveRotated120",
        "12.png:shape2:moveRotated120",
        "13.png:shape2:moveRotated120",
        "14.png:shape2:moveRotated120",
        "15.png:shape3:moveRotated120",
        "16.png:shape3:moveRotated120",
        "17.png:shape3:moveRotated120",
        "18.png:shape3:moveRotated120",
        "19.png:shape3:moveRotated120",
        "20.png:shape3:moveRotated120",
        "21.png:shape3:moveRotated120",
        "22.png:shape4:moveRotated120",
        "23.png:shape4:moveRotated120",
        "24.png:shape4:moveRotated120",
        "25.png:shape4:moveRotated120",
        "26.png:shape4:moveRotated120",
        "27.png:shape4:moveRotated120",
        "28.png:shape4:moveRotated120",
        "1.png:shape1:moveRotated135",
        "2.png:shape1:moveRotated135",
        "3.png:shape1:moveRotated135",
        "4.png:shape1:moveRotated135",
        "5.png:shape1:moveRotated135",
        "6.png:shape1:moveRotated135",
        "7.png:shape1:moveRotated135",
        "8.png:shape2:moveRotated135",
        "9.png:shape2:moveRotated135",
        "10.png:shape2:moveRotated135",
        "11.png:shape2:moveRotated135",
        "12.png:shape2:moveRotated135",
        "13.png:shape2:moveRotated135",
        "14.png:shape2:moveRotated135",
        "15.png:shape3:moveRotated135",
        "16.png:shape3:moveRotated135",
        "17.png:shape3:moveRotated135",
        "18.png:shape3:moveRotated135",
        "19.png:shape3:moveRotated135",
        "20.png:shape3:moveRotated135",
        "21.png:shape3:moveRotated135",
        "22.png:shape4:moveRotated135",
        "23.png:shape4:moveRotated135",
        "24.png:shape4:moveRotated135",
        "25.png:shape4:moveRotated135",
        "26.png:shape4:moveRotated135",
        "27.png:shape4:moveRotated135",
        "28.png:shape4:moveRotated135",
        "1.png:shape1:moveRotated150",
        "2.png:shape1:moveRotated150",
        "3.png:shape1:moveRotated150",
        "4.png:shape1:moveRotated150",
        "5.png:shape1:moveRotated150",
        "6.png:shape1:moveRotated150",
        "7.png:shape1:moveRotated150",
        "8.png:shape2:moveRotated150",
        "9.png:shape2:moveRotated150",
        "10.png:shape2:moveRotated150",
        "11.png:shape2:moveRotated150",
        "12.png:shape2:moveRotated150",
        "13.png:shape2:moveRotated150",
        "14.png:shape2:moveRotated150",
        "15.png:shape3:moveRotated150",
        "16.png:shape3:moveRotated150",
        "17.png:shape3:moveRotated150",
        "18.png:shape3:moveRotated150",
        "19.png:shape3:moveRotated150",
        "20.png:shape3:moveRotated150",
        "21.png:shape3:moveRotated150",
        "22.png:shape4:moveRotated150",
        "23.png:shape4:moveRotated150",
        "24.png:shape4:moveRotated150",
        "25.png:shape4:moveRotated150",
        "26.png:shape4:moveRotated150",
        "27.png:shape4:moveRotated150",
        "28.png:shape4:moveRotated150",
        "1.png:shape1:moveRotated165",
        "2.png:shape1:moveRotated165",
        "3.png:shape1:moveRotated165",
        "4.png:shape1:moveRotated165",
        "5.png:shape1:moveRotated165",
        "6.png:shape1:moveRotated165",
        "7.png:shape1:moveRotated165",
        "8.png:shape2:moveRotated165",
        "9.png:shape2:moveRotated165",
        "10.png:shape2:moveRotated165",
        "11.png:shape2:moveRotated165",
        "12.png:shape2:moveRotated165",
        "13.png:shape2:moveRotated165",
        "14.png:shape2:moveRotated165",
        "15.png:shape3:moveRotated165",
        "16.png:shape3:moveRotated165",
        "17.png:shape3:moveRotated165",
        "18.png:shape3:moveRotated165",
        "19.png:shape3:moveRotated165",
        "20.png:shape3:moveRotated165",
        "21.png:shape3:moveRotated165",
        "22.png:shape4:moveRotated165",
        "23.png:shape4:moveRotated165",
        "24.png:shape4:moveRotated165",
        "25.png:shape4:moveRotated165",
        "26.png:shape4:moveRotated165",
        "27.png:shape4:moveRotated165",
        "28.png:shape4:moveRotated165",
        "1.png:shape1:moveRotated180",
        "2.png:shape1:moveRotated180",
        "3.png:shape1:moveRotated180",
        "4.png:shape1:moveRotated180",
        "5.png:shape1:moveRotated180",
        "6.png:shape1:moveRotated180",
        "7.png:shape1:moveRotated180",
        "8.png:shape2:moveRotated180",
        "9.png:shape2:moveRotated180",
        "10.png:shape2:moveRotated180",
        "11.png:shape2:moveRotated180",
        "12.png:shape2:moveRotated180",
        "13.png:shape2:moveRotated180",
        "14.png:shape2:moveRotated180",
        "15.png:shape3:moveRotated180",
        "16.png:shape3:moveRotated180",
        "17.png:shape3:moveRotated180",
        "18.png:shape3:moveRotated180",
        "19.png:shape3:moveRotated180",
        "20.png:shape3:moveRotated180",
        "21.png:shape3:moveRotated180",
        "22.png:shape4:moveRotated180",
        "23.png:shape4:moveRotated180",
        "24.png:shape4:moveRotated180",
        "25.png:shape4:moveRotated180",
        "26.png:shape4:moveRotated180",
        "27.png:shape4:moveRotated180",
        "28.png:shape4:moveRotated180",
        "1.png:shape1:moveRotated195",
        "2.png:shape1:moveRotated195",
        "3.png:shape1:moveRotated195",
        "4.png:shape1:moveRotated195",
        "5.png:shape1:moveRotated195",
        "6.png:shape1:moveRotated195",
        "7.png:shape1:moveRotated195",
        "8.png:shape2:moveRotated195",
        "9.png:shape2:moveRotated195",
        "10.png:shape2:moveRotated195",
        "11.png:shape2:moveRotated195",
        "12.png:shape2:moveRotated195",
        "13.png:shape2:moveRotated195",
        "14.png:shape2:moveRotated195",
        "15.png:shape3:moveRotated195",
        "16.png:shape3:moveRotated195",
        "17.png:shape3:moveRotated195",
        "18.png:shape3:moveRotated195",
        "19.png:shape3:moveRotated195",
        "20.png:shape3:moveRotated195",
        "21.png:shape3:moveRotated195",
        "22.png:shape4:moveRotated195",
        "23.png:shape4:moveRotated195",
        "24.png:shape4:moveRotated195",
        "25.png:shape4:moveRotated195",
        "26.png:shape4:moveRotated195",
        "27.png:shape4:moveRotated195",
        "28.png:shape4:moveRotated195",
        "1.png:shape1:moveRotated210",
        "2.png:shape1:moveRotated210",
        "3.png:shape1:moveRotated210",
        "4.png:shape1:moveRotated210",
        "5.png:shape1:moveRotated210",
        "6.png:shape1:moveRotated210",
        "7.png:shape1:moveRotated210",
        "8.png:shape2:moveRotated210",
        "9.png:shape2:moveRotated210",
        "10.png:shape2:moveRotated210",
        "11.png:shape2:moveRotated210",
        "12.png:shape2:moveRotated210",
        "13.png:shape2:moveRotated210",
        "14.png:shape2:moveRotated210",
        "15.png:shape3:moveRotated210",
        "16.png:shape3:moveRotated210",
        "17.png:shape3:moveRotated210",
        "18.png:shape3:moveRotated210",
        "19.png:shape3:moveRotated210",
        "20.png:shape3:moveRotated210",
        "21.png:shape3:moveRotated210",
        "22.png:shape4:moveRotated210",
        "23.png:shape4:moveRotated210",
        "24.png:shape4:moveRotated210",
        "25.png:shape4:moveRotated210",
        "26.png:shape4:moveRotated210",
        "27.png:shape4:moveRotated210",
        "28.png:shape4:moveRotated210",
        "1.png:shape1:moveRotated225",
        "2.png:shape1:moveRotated225",
        "3.png:shape1:moveRotated225",
        "4.png:shape1:moveRotated225",
        "5.png:shape1:moveRotated225",
        "6.png:shape1:moveRotated225",
        "7.png:shape1:moveRotated225",
        "8.png:shape2:moveRotated225",
        "9.png:shape2:moveRotated225",
        "10.png:shape2:moveRotated225",
        "11.png:shape2:moveRotated225",
        "12.png:shape2:moveRotated225",
        "13.png:shape2:moveRotated225",
        "14.png:shape2:moveRotated225",
        "15.png:shape3:moveRotated225",
        "16.png:shape3:moveRotated225",
        "17.png:shape3:moveRotated225",
        "18.png:shape3:moveRotated225",
        "19.png:shape3:moveRotated225",
        "20.png:shape3:moveRotated225",
        "21.png:shape3:moveRotated225",
        "22.png:shape4:moveRotated225",
        "23.png:shape4:moveRotated225",
        "24.png:shape4:moveRotated225",
        "25.png:shape4:moveRotated225",
        "26.png:shape4:moveRotated225",
        "27.png:shape4:moveRotated225",
        "28.png:shape4:moveRotated225",
        "1.png:shape1:moveRotated240",
        "2.png:shape1:moveRotated240",
        "3.png:shape1:moveRotated240",
        "4.png:shape1:moveRotated240",
        "5.png:shape1:moveRotated240",
        "6.png:shape1:moveRotated240",
        "7.png:shape1:moveRotated240",
        "8.png:shape2:moveRotated240",
        "9.png:shape2:moveRotated240",
        "10.png:shape2:moveRotated240",
        "11.png:shape2:moveRotated240",
        "12.png:shape2:moveRotated240",
        "13.png:shape2:moveRotated240",
        "14.png:shape2:moveRotated240",
        "15.png:shape3:moveRotated240",
        "16.png:shape3:moveRotated240",
        "17.png:shape3:moveRotated240",
        "18.png:shape3:moveRotated240",
        "19.png:shape3:moveRotated240",
        "20.png:shape3:moveRotated240",
        "21.png:shape3:moveRotated240",
        "22.png:shape4:moveRotated240",
        "23.png:shape4:moveRotated240",
        "24.png:shape4:moveRotated240",
        "25.png:shape4:moveRotated240",
        "26.png:shape4:moveRotated240",
        "27.png:shape4:moveRotated240",
        "28.png:shape4:moveRotated240",
        "1.png:shape1:moveRotated255",
        "2.png:shape1:moveRotated255",
        //        "3.png:shape1:version1:moveRotated255",
        "3.png:shape1:moveRotated255",
        "4.png:shape1:moveRotated255",
        "5.png:shape1:moveRotated255",
        "6.png:shape1:moveRotated255",
        "7.png:shape1:moveRotated255",
        //        "8.png:shape2:version1:version2:moveRotated255",
        "8.png:shape2:moveRotated255",
        "9.png:shape2:moveRotated255",
        "10.png:shape2:moveRotated255",
        "11.png:shape2:moveRotated255",
        //        "11.png:shape2:version2:version2zero:moveRotated255",
        "12.png:shape2:moveRotated255",
        "13.png:shape2:moveRotated255",
        "14.png:shape2:moveRotated255",
        "15.png:shape3:moveRotated255",
        "16.png:shape3:moveRotated255",
        //        "16.png:shape3:version1:moveRotated255",
        "17.png:shape3:moveRotated255",
        "18.png:shape3:moveRotated255",
        "19.png:shape3:moveRotated255",
        "20.png:shape3:moveRotated255",
        "21.png:shape3:moveRotated255",
        "22.png:shape4:moveRotated255",
        "23.png:shape4:moveRotated255",
        "24.png:shape4:moveRotated255",
        "25.png:shape4:moveRotated255",
        "26.png:shape4:moveRotated255",
        "27.png:shape4:moveRotated255",
        "28.png:shape4:moveRotated255",
        "1.png:shape1:moveRotated270",
        "2.png:shape1:moveRotated270",
        "3.png:shape1:moveRotated270",
        "4.png:shape1:moveRotated270",
        "5.png:shape1:moveRotated270",
        "6.png:shape1:moveRotated270",
        "7.png:shape1:moveRotated270",
        "8.png:shape2:moveRotated270",
        "9.png:shape2:moveRotated270",
        "10.png:shape2:moveRotated270",
        "11.png:shape2:moveRotated270",
        "12.png:shape2:moveRotated270",
        "13.png:shape2:moveRotated270",
        "14.png:shape2:moveRotated270",
        "15.png:shape3:moveRotated270",
        "16.png:shape3:moveRotated270",
        "17.png:shape3:moveRotated270",
        "18.png:shape3:moveRotated270",
        "19.png:shape3:moveRotated270",
        "20.png:shape3:moveRotated270",
        "21.png:shape3:moveRotated270",
        "22.png:shape4:moveRotated270",
        "23.png:shape4:moveRotated270",
        "24.png:shape4:moveRotated270",
        "25.png:shape4:moveRotated270",
        "26.png:shape4:moveRotated270",
        "27.png:shape4:moveRotated270",
        "28.png:shape4:moveRotated270",
        "1.png:shape1:moveRotated285",
        "2.png:shape1:moveRotated285",
        "3.png:shape1:moveRotated285",
        "4.png:shape1:moveRotated285",
        "5.png:shape1:moveRotated285",
        "6.png:shape1:moveRotated285",
        "7.png:shape1:moveRotated285",
        "8.png:shape2:moveRotated285",
        "9.png:shape2:moveRotated285",
        "10.png:shape2:moveRotated285",
        "11.png:shape2:moveRotated285",
        "12.png:shape2:moveRotated285",
        "13.png:shape2:moveRotated285",
        "14.png:shape2:moveRotated285",
        "15.png:shape3:moveRotated285",
        "16.png:shape3:moveRotated285",
        "17.png:shape3:moveRotated285",
        "18.png:shape3:moveRotated285",
        "19.png:shape3:moveRotated285",
        "20.png:shape3:moveRotated285",
        "21.png:shape3:moveRotated285",
        "22.png:shape4:moveRotated285",
        "23.png:shape4:moveRotated285",
        "24.png:shape4:moveRotated285",
        "25.png:shape4:moveRotated285",
        "26.png:shape4:moveRotated285",
        "27.png:shape4:moveRotated285",
        "28.png:shape4:moveRotated285",
        "1.png:shape1:moveRotated300",
        "2.png:shape1:moveRotated300",
        "3.png:shape1:moveRotated300",
        "4.png:shape1:moveRotated300",
        "5.png:shape1:moveRotated300",
        "6.png:shape1:moveRotated300",
        "7.png:shape1:moveRotated300",
        "8.png:shape2:moveRotated300",
        "9.png:shape2:moveRotated300",
        "10.png:shape2:moveRotated300",
        "11.png:shape2:moveRotated300",
        "12.png:shape2:moveRotated300",
        "13.png:shape2:moveRotated300",
        "14.png:shape2:moveRotated300",
        "15.png:shape3:moveRotated300",
        "16.png:shape3:moveRotated300",
        "17.png:shape3:moveRotated300",
        "18.png:shape3:moveRotated300",
        "19.png:shape3:moveRotated300",
        "20.png:shape3:moveRotated300",
        "21.png:shape3:moveRotated300",
        "22.png:shape4:moveRotated300",
        "23.png:shape4:moveRotated300",
        "24.png:shape4:moveRotated300",
        "25.png:shape4:moveRotated300",
        "26.png:shape4:moveRotated300",
        "27.png:shape4:moveRotated300",
        "28.png:shape4:moveRotated300",
        "1.png:shape1:moveRotated315",
        "2.png:shape1:moveRotated315",
        "3.png:shape1:moveRotated315",
        "4.png:shape1:moveRotated315",
        "5.png:shape1:moveRotated315",
        "6.png:shape1:moveRotated315",
        "7.png:shape1:moveRotated315",
        "8.png:shape2:moveRotated315",
        "9.png:shape2:moveRotated315",
        "10.png:shape2:moveRotated315",
        "11.png:shape2:moveRotated315",
        "12.png:shape2:moveRotated315",
        "13.png:shape2:moveRotated315",
        "14.png:shape2:moveRotated315",
        "15.png:shape3:moveRotated315",
        "16.png:shape3:moveRotated315",
        "17.png:shape3:moveRotated315",
        "18.png:shape3:moveRotated315",
        "19.png:shape3:moveRotated315",
        "20.png:shape3:moveRotated315",
        "21.png:shape3:moveRotated315",
        "22.png:shape4:moveRotated315",
        "23.png:shape4:moveRotated315",
        "24.png:shape4:moveRotated315",
        "25.png:shape4:moveRotated315",
        "26.png:shape4:moveRotated315",
        "27.png:shape4:moveRotated315",
        "28.png:shape4:moveRotated315",
        "1.png:shape1:moveRotated330",
        "2.png:shape1:moveRotated330",
        "3.png:shape1:moveRotated330",
        "4.png:shape1:moveRotated330",
        "5.png:shape1:moveRotated330",
        "6.png:shape1:moveRotated330",
        "7.png:shape1:moveRotated330",
        "8.png:shape2:moveRotated330",
        "9.png:shape2:moveRotated330",
        "10.png:shape2:moveRotated330",
        "11.png:shape2:moveRotated330",
        "12.png:shape2:moveRotated330",
        "13.png:shape2:moveRotated330",
        "14.png:shape2:moveRotated330",
        "15.png:shape3:moveRotated330",
        "16.png:shape3:moveRotated330",
        "17.png:shape3:moveRotated330",
        "18.png:shape3:moveRotated330",
        "19.png:shape3:moveRotated330",
        "20.png:shape3:moveRotated330",
        "21.png:shape3:moveRotated330",
        "22.png:shape4:moveRotated330",
        "23.png:shape4:moveRotated330",
        "24.png:shape4:moveRotated330",
        "25.png:shape4:moveRotated330",
        "26.png:shape4:moveRotated330",
        "27.png:shape4:moveRotated330",
        "28.png:shape4:moveRotated330",
        "1.png:shape1:moveRotated345",
        "2.png:shape1:moveRotated345",
        "3.png:shape1:moveRotated345",
        "4.png:shape1:moveRotated345",
        "5.png:shape1:moveRotated345",
        "6.png:shape1:moveRotated345",
        "7.png:shape1:moveRotated345",
        "8.png:shape2:moveRotated345",
        "9.png:shape2:moveRotated345",
        "10.png:shape2:moveRotated345",
        "11.png:shape2:moveRotated345",
        "12.png:shape2:moveRotated345",
        "13.png:shape2:moveRotated345",
        "14.png:shape2:moveRotated345",
        "15.png:shape3:moveRotated345",
        "16.png:shape3:moveRotated345",
        "17.png:shape3:moveRotated345",
        "18.png:shape3:moveRotated345",
        "19.png:shape3:moveRotated345",
        "20.png:shape3:moveRotated345",
        "21.png:shape3:moveRotated345",
        "22.png:shape4:moveRotated345",
        "23.png:shape4:moveRotated345",
        "24.png:shape4:moveRotated345",
        "25.png:shape4:moveRotated345",
        "26.png:shape4:moveRotated345",
        "27.png:shape4:moveRotated345",
        "28.png:shape4:moveRotated345",
        "1.png:shape1:moveRotated360",
        "2.png:shape1:moveRotated360",
        "3.png:shape1:moveRotated360",
        "4.png:shape1:moveRotated360",
        "5.png:shape1:moveRotated360",
        "6.png:shape1:moveRotated360",
        "7.png:shape1:moveRotated360",
        "8.png:shape2:moveRotated360",
        "9.png:shape2:moveRotated360",
        "10.png:shape2:moveRotated360",
        "11.png:shape2:moveRotated360",
        "12.png:shape2:moveRotated360",
        "13.png:shape2:moveRotated360",
        "14.png:shape2:moveRotated360",
        "15.png:shape3:moveRotated360",
        "16.png:shape3:moveRotated360",
        "17.png:shape3:moveRotated360",
        "18.png:shape3:moveRotated360",
        "19.png:shape3:moveRotated360",
        "20.png:shape3:moveRotated360",
        "21.png:shape3:moveRotated360",
        "22.png:shape4:moveRotated360",
        "23.png:shape4:moveRotated360",
        "24.png:shape4:moveRotated360",
        "25.png:shape4:moveRotated360",
        "26.png:shape4:moveRotated360",
        "27.png:shape4:moveRotated360",
        "28.png:shape4:moveRotated360"
    };

    // @todo: server shared variables to be used in animations and interactions concurrently displayed on multiple users devices 
    public WizardData getWizardData() {
        WizardData wizardData = new WizardData();
        wizardData.setAppName("MultiParticipant");
        wizardData.setShowMenuBar(true);
        wizardData.setObfuscateScreenNames(false);

        final WizardAgreementScreen wizardAgreementScreen = new WizardAgreementScreen("Agreement", "<b>This is a prototype multiparticipant experiment.</b><br/><br/>"
                + "With this prototype you can:<br/>"
                + "<li>view the group activity and add dummy users to a group for testing purposes <a href='/multiparticipant/grouptestpage.html'>/multiparticipant/grouptestpage.html</a>.</li>"
                + "<li>erase the local data for this browser <a href='/multiparticipant?debug'>/multiparticipant?debug</a></li>"
                + "<li>random data can be generated with the testing robot <a href='/multiparticipant/TestingFrame.html'>/multiparticipant/TestingFrame.html</a></li><br/>"
                + "<li>eight users intracting can be randomly simulated testing robot <a href='/multiparticipant/grouptestframes.html'>/multiparticipant/grouptestframes.html</a></li><br/>"
                + "The group name must be allocated with the following with <a href='/multiparticipant/?group=a_group_name'>/multiparticipant/?group=a_group_name</a> where a_group_name should be replaced with a suitable string. A second user can be tested on one computer via the incognito browser window with this link, providing the group name matches.<br/><br/>"
                + "There needs to be eight users connected for the group process to begin. Once a group is full, any subsequent users will need to be allocated a different group via the a_group_name parameter.<br/><br/><br/>"
                + "You can view the collected group data with <a href='/multiparticipant-admin/groupdataviewer'>/multiparticipant-admin/groupdataviewer</a> with the user and password you have been supplied.<br/><br/><br/>",
                "Continue");
        final WizardAboutScreen wizardAboutScreen = new WizardAboutScreen(true);

        final WizardEditUserScreen wizardEditUserScreen = new WizardEditUserScreen();
        wizardEditUserScreen.setScreenTitle("Edit User");
        wizardEditUserScreen.setMenuLabel("Edit User");
        wizardEditUserScreen.setScreenTag("Edit_User");
        wizardEditUserScreen.setNextButton("Next");
        wizardEditUserScreen.setSendData(true);
        wizardEditUserScreen.setOn_Error_Text("Could not contact the server, please check your internet connection and try again.");
        wizardEditUserScreen.setAgeField();
        wizardEditUserScreen.setFirstNameField();
        wizardEditUserScreen.setGenderField();
        wizardEditUserScreen.setWorkerIdField();

        final String groupMembers4 = "A,B,C,D";
        final String groupMembers8 = "A,B,C,D,E,F,G,H";
        final String textEntryPhaseRoles4 = "A,C:-:-:B,D:-:-";
        final String textEntryPhaseRoles8 = "A,C,E,G:-:-:B,D,F,H:-:-";
        final String textEntryPhaseText = "The producer sees the stimulus and enters some text";
        final String textWaitPhaseRoles4 = "B,D:-:-:A,C:-:-";
        final String textWaitPhaseRoles8 = "B,D,F,H:-:-:A,C,E,G:-:-";
        final String textWaitPhaseText = "The guesser waits for the producer";
        final String gridWaitPhaseRoles4 = "-:A,C:-:-:B,D:-";
        final String gridWaitPhaseRoles8 = "-:A,C,E,G:-:-:B,D,F,H:-";
        final String gridWaitPhaseText = "The producer waits for the guesser";
        final String responseGridPhaseRoles4 = "-:B,D:-:-:A,C:-";
        final String responseGridPhaseRoles8 = "-:B,D,F,H:-:-:A,C,E,G:-";
        final String responseGridPhaseText = "The guesser sees the text with a grid of stimuli, from which they select one based on the text";
        final String mutualFeedbackPhaseRoles4 = "-:-:A,B,C,D:-:-:A,B,C,D";
        final String mutualFeedbackPhaseRoles8 = "-:-:A,B,C,D,E,F,G,H:-:-:A,B,C,D,E,F,G,H";
        final String mutualFeedbackPhaseText = "The guesser and producer see the allocated stimuli with the guessers selected stimuli and the text from the producer. Following this the next stimulus is selected and the flow returns to activity 0.";

        final WizardMultiParticipantScreen round0MultiParticipantScreen4 = new WizardMultiParticipantScreen("Round 0 - 4",
                groupMembers4,
                "A,B,C,D",
                "A:-:B:-:C:-:D:-",
                "The producer sees the stimulus and enters some text",
                "B,C,D:-:A,C,D:-:B,A,D:-:B,C,A:-",
                true,
                "All other participants wait for the producer",
                "-:A:-:B:-:C:-:D",
                "The producer waits for all other participants",
                "",
                "This phase is not used in this screen",
                "",
                "This phase is not used in this screen",
                "-:B,C,D:-:A,C,D:-:B,A,D:-:B,C,A",
                "The stimulus and the producers text are shown to all other participants", 23);
        final WizardMultiParticipantScreen round0MultiParticipantScreen8 = new WizardMultiParticipantScreen("Round 0 - 8",
                groupMembers8,
                "A,B,C,D,E,F,G,H",
                "A:-:B:-:C:-:D:-:E:-:F:-:G:-:H:-",
                "The producer sees the stimulus and enters some text",
                "B,C,D,E,F,G,H:-:A,C,D,E,F,G,H:-:B,A,D,E,F,G,H:-:B,C,A,E,F,G,H:-:B,C,D,A,F,G,H:-:B,C,D,E,A,G,H:-:B,C,D,E,F,A,H:-:B,C,D,E,F,G,A:-",
                true,
                "All other participants wait for the producer",
                "-:A:-:B:-:C:-:D:-:E:-:F:-:G:-:H",
                "The producer waits for all other participants",
                "",
                "This phase is not used in this screen",
                "",
                "This phase is not used in this screen",
                "-:B,C,D,E,F,G,H:-:A,C,D,E,F,G,H:-:B,A,D,E,F,G,H:-:B,C,A,E,F,G,H:-:B,C,D,A,F,G,H:-:B,C,D,E,A,G,H:-:B,C,D,E,F,A,H:-:B,C,D,E,F,G,A",
                "The stimulus and the producers text are shown to all other participants", 23);
        final WizardMultiParticipantScreen round1MultiParticipantScreen4 = new WizardMultiParticipantScreen("Round 1 - 4",
                groupMembers4,
                "A,B|C,D",
                textEntryPhaseRoles4,
                textEntryPhaseText,
                textWaitPhaseRoles4,
                false,
                textWaitPhaseText,
                gridWaitPhaseRoles4,
                gridWaitPhaseText,
                responseGridPhaseRoles4,
                responseGridPhaseText,
                mutualFeedbackPhaseRoles4,
                mutualFeedbackPhaseText,
                "",
                "This phase is not used in this screen", 23);
        final WizardMultiParticipantScreen round1MultiParticipantScreen8 = new WizardMultiParticipantScreen("Round 1 - 8",
                groupMembers8,
                "A,B|C,D|E,F|G,H",
                textEntryPhaseRoles8,
                textEntryPhaseText,
                textWaitPhaseRoles8,
                false,
                textWaitPhaseText,
                gridWaitPhaseRoles8,
                gridWaitPhaseText,
                responseGridPhaseRoles8,
                responseGridPhaseText,
                mutualFeedbackPhaseRoles8,
                mutualFeedbackPhaseText,
                "",
                "This phase is not used in this screen", 23);
        final WizardMultiParticipantScreen round2MultiParticipantScreen4 = new WizardMultiParticipantScreen("Round 2 - 4",
                groupMembers4,
                "B,C|D,A",
                textEntryPhaseRoles4,
                textEntryPhaseText,
                textWaitPhaseRoles4,
                false,
                textWaitPhaseText,
                gridWaitPhaseRoles4,
                gridWaitPhaseText,
                responseGridPhaseRoles4,
                responseGridPhaseText,
                mutualFeedbackPhaseRoles4,
                mutualFeedbackPhaseText,
                "",
                "This phase is not used in this screen", 23);
        final WizardMultiParticipantScreen round2MultiParticipantScreen8 = new WizardMultiParticipantScreen("Round 2 - 8",
                groupMembers8,
                "B,C|D,E|F,G|H,A",
                textEntryPhaseRoles8,
                textEntryPhaseText,
                textWaitPhaseRoles8,
                false,
                textWaitPhaseText,
                gridWaitPhaseRoles8,
                gridWaitPhaseText,
                responseGridPhaseRoles8,
                responseGridPhaseText,
                mutualFeedbackPhaseRoles8,
                mutualFeedbackPhaseText,
                "",
                "This phase is not used in this screen", 23);
        round0MultiParticipantScreen4.setStimuliSet(stimuliArray);
        round1MultiParticipantScreen4.setStimuliSet(stimuliArray);
        round2MultiParticipantScreen4.setStimuliSet(stimuliArray);
        round0MultiParticipantScreen8.setStimuliSet(stimuliArray);
        round1MultiParticipantScreen8.setStimuliSet(stimuliArray);
        round2MultiParticipantScreen8.setStimuliSet(stimuliArray);
        round0MultiParticipantScreen4.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");
        round1MultiParticipantScreen4.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");
        round2MultiParticipantScreen4.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");
        round0MultiParticipantScreen8.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");
        round1MultiParticipantScreen8.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");
        round2MultiParticipantScreen8.setStimulusFreeText(true, "[^0-9^S^J^s^j^C^c^V^v^W^w^T^t^Z^z^Y^y^X^x]{2,}", "Vul een woord in de tekstbox in dat volgens u het best aan het einde van de zin past.");

        WizardCompletionScreen completionScreen = new WizardCompletionScreen("Einde van het experiment", false, false,
                //                                "Wil nog iemand op dit apparaat deelnemen aan dit onderzoek, klik dan op de onderstaande knop.",
                "Einde van het experiment1",
                "Opnieuw beginnen",
                "Einde van het experiment2",
                "Geen verbinding met de server. Controleer alstublieft uw internetverbinding en probeer het opnieuw.",
                "Probeer opnieuw");
        WizardMenuScreen menuScreen4or8Members = new WizardMenuScreen("GroupSizeMenu", "GroupSizeMenu", "GroupSizeMenu");

        wizardData.addScreen(wizardAgreementScreen);
        wizardData.addScreen(wizardEditUserScreen);
        wizardData.addScreen(menuScreen4or8Members);
        wizardData.addScreen(round0MultiParticipantScreen4);
        wizardData.addScreen(round1MultiParticipantScreen4);
        wizardData.addScreen(round2MultiParticipantScreen4);
        wizardData.addScreen(round0MultiParticipantScreen8);
        wizardData.addScreen(round1MultiParticipantScreen8);
        wizardData.addScreen(round2MultiParticipantScreen8);
        wizardData.addScreen(wizardAboutScreen);
        wizardData.addScreen(completionScreen);

        wizardAgreementScreen.setNextWizardScreen(wizardEditUserScreen);
        wizardEditUserScreen.setBackWizardScreen(wizardAgreementScreen);
        wizardEditUserScreen.setNextWizardScreen(menuScreen4or8Members);
        menuScreen4or8Members.addTargetScreen(round0MultiParticipantScreen4);
        menuScreen4or8Members.addTargetScreen(round0MultiParticipantScreen8);
        round0MultiParticipantScreen4.setNextWizardScreen(round1MultiParticipantScreen4);
        round0MultiParticipantScreen8.setNextWizardScreen(round1MultiParticipantScreen8);
        round1MultiParticipantScreen4.setNextWizardScreen(round2MultiParticipantScreen4);
        round1MultiParticipantScreen8.setNextWizardScreen(round2MultiParticipantScreen8);
        round0MultiParticipantScreen4.setBackWizardScreen(wizardAgreementScreen);
        round0MultiParticipantScreen8.setBackWizardScreen(wizardAgreementScreen);
        round1MultiParticipantScreen4.setBackWizardScreen(wizardAgreementScreen);
        round1MultiParticipantScreen8.setBackWizardScreen(wizardAgreementScreen);
        round2MultiParticipantScreen4.setBackWizardScreen(wizardAgreementScreen);
        round2MultiParticipantScreen8.setBackWizardScreen(wizardAgreementScreen);
        round2MultiParticipantScreen4.setNextWizardScreen(completionScreen);
        round2MultiParticipantScreen8.setNextWizardScreen(completionScreen);
//        endTextScreen.setNextWizardScreen(wizardAboutScreen);
        wizardAboutScreen.setBackWizardScreen(wizardAgreementScreen);

        return wizardData;
    }

    public Experiment getExperiment() {
        return wizardController.getExperiment(getWizardData());
    }
}
