/*
 * Copyright (C) 2018 Max Planck Institute for Psycholinguistics, Nijmegen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.frinex.adaptivevocabularyassessment.client.service.audioaspool;

/**
 *
 * @author olhshk
 */
public class AudioPool2 {

    public static final String[] TRIAL_ROWS={"word:vloer,targetNonWord:smoer,nOfSyllables:1,condition:Target-only,length:3,Word1:deebral,Word2:smoer,Word3:wijp,Word4:,Word5:,Word6:,foil:",
"word:pauw,targetNonWord:paud,nOfSyllables:1,condition:Target-only,length:3,Word1:rolscheegt,Word2:paud,Word3:staap,Word4:,Word5:,Word6:,foil:",
"word:krik,targetNonWord:grik,nOfSyllables:1,condition:Target-only,length:3,Word1:spank,Word2:grik,Word3:pintein,Word4:,Word5:,Word6:,foil:",
"word:schelp,targetNonWord:schess,nOfSyllables:1,condition:Target-only,length:3,Word1:rim,Word2:schess,Word3:werelglal,Word4:,Word5:,Word6:,foil:",
"word:slee,targetNonWord:gree,nOfSyllables:1,condition:Target-only,length:3,Word1:brachter,Word2:gree,Word3:straak,Word4:,Word5:,Word6:,foil:",
"word:mand,targetNonWord:maks,nOfSyllables:1,condition:Target-only,length:3,Word1:palfhoom,Word2:maks,Word3:jeer,Word4:,Word5:,Word6:,foil:",
"word:tang,targetNonWord:mang,nOfSyllables:1,condition:Target-only,length:3,Word1:lartmat,Word2:mang,Word3:bleeuw,Word4:,Word5:,Word6:,foil:",
"word:vaas,targetNonWord:zaas,nOfSyllables:1,condition:Target-only,length:3,Word1:pinjat,Word2:zaas,Word3:dieg,Word4:,Word5:,Word6:,foil:",
"word:zweep,targetNonWord:speep,nOfSyllables:1,condition:Target-only,length:3,Word1:hocket,Word2:speep,Word3:wooi,Word4:,Word5:,Word6:,foil:",
"word:vork,targetNonWord:zork,nOfSyllables:1,condition:Target-only,length:3,Word1:mewer,Word2:zork,Word3:stroor,Word4:,Word5:,Word6:,foil:",
"word:kam,targetNonWord:kag,nOfSyllables:1,condition:Target-only,length:3,Word1:algel,Word2:kag,Word3:knoot,Word4:,Word5:,Word6:,foil:",
"word:sjaal,targetNonWord:vraal,nOfSyllables:1,condition:Target-only,length:3,Word1:pruif,Word2:vraal,Word3:gesoe,Word4:,Word5:,Word6:,foil:",
"word:wolk,targetNonWord:woch,nOfSyllables:1,condition:Target-only,length:3,Word1:graap,Word2:woch,Word3:aardwoe,Word4:,Word5:,Word6:,foil:",
"word:kreeft,targetNonWord:kreens,nOfSyllables:1,condition:Target-only,length:3,Word1:huim,Word2:kreens,Word3:schismel,Word4:,Word5:,Word6:,foil:",
"word:kaars,targetNonWord:kiers,nOfSyllables:1,condition:Target-only,length:3,Word1:hog,Word2:kiers,Word3:waga,Word4:,Word5:,Word6:,foil:",
"word:hert,targetNonWord:hets,nOfSyllables:1,condition:Target-only,length:3,Word1:sperf,Word2:hets,Word3:nijmwaard,Word4:,Word5:,Word6:,foil:",
"word:schaar,targetNonWord:schoer,nOfSyllables:1,condition:Target-only,length:3,Word1:brin,Word2:schoer,Word3:kneeuwlan,Word4:,Word5:,Word6:,foil:",
"word:kraan,targetNonWord:blaan,nOfSyllables:1,condition:Target-only,length:3,Word1:stolf,Word2:blaan,Word3:caimug,Word4:,Word5:,Word6:,foil:",
"word:kers,targetNonWord:hers,nOfSyllables:1,condition:Target-only,length:4,Word1:geider,Word2:hers,Word3:atgraus,Word4:hamp,Word5:,Word6:,foil:",
"word:kurk,targetNonWord:skee,nOfSyllables:1,condition:Target-only,length:4,Word1:pif,Word2:skee,Word3:wadees,Word4:landhoeg,Word5:,Word6:,foil:",
"word:vlot,targetNonWord:vrot,nOfSyllables:1,condition:Target-only,length:4,Word1:spomwel,Word2:vrot,Word3:akakos,Word4:borts,Word5:,Word6:,foil:",
"word:pruik,targetNonWord:proek,nOfSyllables:1,condition:Target-only,length:4,Word1:doljeen,Word2:proek,Word3:klek,Word4:spomset,Word5:,Word6:,foil:",
"word:schaap,targetNonWord:schuip,nOfSyllables:1,condition:Target-only,length:4,Word1:wamoel,Word2:schuip,Word3:balstel,Word4:res,Word5:,Word6:,foil:",
"word:wiel,targetNonWord:diel,nOfSyllables:1,condition:Target-only,length:4,Word1:schuik,Word2:diel,Word3:trauster,Word4:pozaat,Word5:,Word6:,foil:",
"word:rok,targetNonWord:ror,nOfSyllables:1,condition:Target-only,length:4,Word1:schir,Word2:ror,Word3:nekla,Word4:draxtor,Word5:,Word6:,foil:",
"word:vos,targetNonWord:ves,nOfSyllables:1,condition:Target-only,length:4,Word1:almak,Word2:ves,Word3:calg,Word4:ijnhooid,Word5:,Word6:,foil:",
"word:spin,targetNonWord:klin,nOfSyllables:1,condition:Target-only,length:4,Word1:heut,Word2:klin,Word3:beno,Word4:pommoon,Word5:,Word6:,foil:",
"word:harp,targetNonWord:harf,nOfSyllables:1,condition:Target-only,length:4,Word1:tenreel,Word2:raardkust,Word3:harf,Word4:gaak,Word5:,Word6:,foil:",
"word:zwaan,targetNonWord:praan,nOfSyllables:1,condition:Target-only,length:4,Word1:mork,Word2:siekoed,Word3:praan,Word4:beerban,Word5:,Word6:,foil:",
"word:geit,targetNonWord:deit,nOfSyllables:1,condition:Target-only,length:4,Word1:plaai,Word2:remel,Word3:deit,Word4:bageen,Word5:,Word6:,foil:",
"word:tak,targetNonWord:tek,nOfSyllables:1,condition:Target-only,length:4,Word1:zweeger,Word2:olker,Word3:tek,Word4:kig,Word5:,Word6:,foil:",
"word:worst,targetNonWord:porst,nOfSyllables:1,condition:Target-only,length:4,Word1:cofo,Word2:gruin,Word3:porst,Word4:petloog,Word5:,Word6:,foil:",
"word:eend,targetNonWord:oend,nOfSyllables:1,condition:Target-only,length:4,Word1:fonguin,Word2:laaps,Word3:oend,Word4:spunel,Word5:,Word6:,foil:",
"word:bijl,targetNonWord:lijl,nOfSyllables:1,condition:Target-only,length:4,Word1:schifthad,Word2:garlon,Word3:lijl,Word4:dreel,Word5:,Word6:,foil:",
"word:pan,targetNonWord:nan,nOfSyllables:1,condition:Target-only,length:4,Word1:susraan,Word2:breen,Word3:nan,Word4:eekhaaid,Word5:,Word6:,foil:",
"word:haai,targetNonWord:hoei,nOfSyllables:1,condition:Target-only,length:4,Word1:jerg,Word2:cigroon,Word3:hoei,Word4:lordel,Word5:,Word6:,foil:",
"word:peer,targetNonWord:reer,nOfSyllables:1,condition:Target-only,length:5,Word1:omvost,Word2:reer,Word3:drits,Word4:bilwoon,Word5:pild,Word6:,foil:",
"word:duim,targetNonWord:tuim,nOfSyllables:1,condition:Target-only,length:5,Word1:drander,Word2:tuim,Word3:laber,Word4:kloes,Word5:zuin,Word6:,foil:",
"word:helm,targetNonWord:hern,nOfSyllables:1,condition:Target-only,length:5,Word1:delk,Word2:hern,Word3:wazon,Word4:tuip,Word5:veser,Word6:,foil:",
"word:muis,targetNonWord:muin,nOfSyllables:1,condition:Target-only,length:5,Word1:blan,Word2:muin,Word3:wemp,Word4:euzer,Word5:knekgel,Word6:,foil:",
"word:baard,targetNonWord:baaks,nOfSyllables:1,condition:Target-only,length:5,Word1:sinier,Word2:baaks,Word3:ern,Word4:has,Word5:zates,Word6:,foil:",
"word:strik,targetNonWord:strok,nOfSyllables:1,condition:Target-only,length:5,Word1:torlier,Word2:geun,Word3:strok,Word4:tarp,Word5:furilt,Word6:,foil:",
"word:clown,targetNonWord:cloys,nOfSyllables:1,condition:Target-only,length:5,Word1:popfouk,Word2:lauk,Word3:cloys,Word4:leuder,Word5:belp,Word6:,foil:",
"word:haak,targetNonWord:hijk,nOfSyllables:1,condition:Target-only,length:5,Word1:mozing,Word2:ammel,Word3:hijk,Word4:vap,Word5:riel,Word6:,foil:",
"word:spook,targetNonWord:spuik,nOfSyllables:1,condition:Target-only,length:5,Word1:gerf,Word2:taud,Word3:spuik,Word4:gideer,Word5:lobat,Word6:,foil:",
"word:pet,targetNonWord:tet,nOfSyllables:1,condition:Target-only,length:5,Word1:kleuk,Word2:kiazont,Word3:tet,Word4:schrins,Word5:tiaka,Word6:,foil:",
"word:das,targetNonWord:dap,nOfSyllables:1,condition:Target-only,length:5,Word1:cowtou,Word2:kest,Word3:dap,Word4:poeger,Word5:wos,Word6:,foil:",
"word:slak,targetNonWord:slas,nOfSyllables:1,condition:Target-only,length:5,Word1:laanzan,Word2:halg,Word3:jirsel,Word4:slas,Word5:goe,Word6:,foil:",
"word:schoen,targetNonWord:schien,nOfSyllables:1,condition:Target-only,length:5,Word1:spraf,Word2:blamsem,Word3:pandanst,Word4:schien,Word5:hon,Word6:,foil:",
"word:bloem,targetNonWord:blijm,nOfSyllables:1,condition:Target-only,length:5,Word1:bramp,Word2:stenk,Word3:zwesbag,Word4:blijm,Word5:schekder,Word6:,foil:",
"word:ton,targetNonWord:mon,nOfSyllables:1,condition:Target-only,length:5,Word1:speemel,Word2:schrag,Word3:kopeen,Word4:mon,Word5:spaaf,Word6:,foil:",
"word:pijp,targetNonWord:puip,nOfSyllables:1,condition:Target-only,length:5,Word1:hir,Word2:dotting,Word3:wams,Word4:puip,Word5:garsen,Word6:,foil:",
"word:kroon,targetNonWord:broon,nOfSyllables:1,condition:Target-only,length:5,Word1:warker,Word2:lepen,Word3:pluif,Word4:broon,Word5:pir,Word6:,foil:",
"word:uil,targetNonWord:ool,nOfSyllables:1,condition:Target-only,length:6,Word1:opwijp,Word2:ool,Word3:zoeg,Word4:afschoek,Word5:bezwop,Word6:kra ,foil:",
"word:leeuw,targetNonWord:heeuw,nOfSyllables:1,condition:Target-only,length:6,Word1:ginler,Word2:heeuw,Word3:palk,Word4:sallaat,Word5:gilp,Word6:gesaar,foil:",
"word:draak,targetNonWord:praak,nOfSyllables:1,condition:Target-only,length:6,Word1:kilk,Word2:praak,Word3:dienel,Word4:scheus,Word5:hoonpoed,Word6:zalgens,foil:",
"word:vlag,targetNonWord:knag,nOfSyllables:1,condition:Target-only,length:6,Word1:spoutel,Word2:knag,Word3:teul,Word4:rusjen,Word5:pacel,Word6:pleig,foil:",
"word:zaag,targetNonWord:gaag,nOfSyllables:1,condition:Target-only,length:6,Word1:dreu,Word2:goelroop,Word3:gaag,Word4:bip,Word5:oekheid,Word6:mechter,foil:",
"word:koe,targetNonWord:kie ,nOfSyllables:1,condition:Target-only,length:6,Word1:mastool,Word2:smees,Word3:kie ,Word4:muipje,Word5:aankol,Word6:sma,foil:",
"word:tank,targetNonWord:pank,nOfSyllables:1,condition:Target-only,length:6,Word1:alktoord,Word2:bawo,Word3:pank,Word4:knaf,Word5:kel,Word6:loofteed,foil:",
"word:kruis,targetNonWord:fluis,nOfSyllables:1,condition:Target-only,length:6,Word1:viet,Word2:tar,Word3:fluis,Word4:eidind,Word5:gruton,Word6:goeling,foil:",
"word:slang,targetNonWord:krang,nOfSyllables:1,condition:Target-only,length:6,Word1:sproor,Word2:dapter,Word3:koomlan,Word4:krang,Word5:goem,Word6:afschaag,foil:",
"word:fiets,targetNonWord:fuits,nOfSyllables:1,condition:Target-only,length:6,Word1:klork,Word2:oorwag,Word3:klies,Word4:fuits,Word5:pernoen,Word6:voorboons,foil:",
"word:plein,targetNonWord:ploen,nOfSyllables:1,condition:Target-only,length:6,Word1:roekwom,Word2:hoel,Word3:inbods,Word4:ploen,Word5:gik,Word6:kievaar,foil:",
"word:kaas,targetNonWord:kaat,nOfSyllables:1,condition:Target-only,length:6,Word1:menk,Word2:waalteed,Word3:voorboorn,Word4:kaat,Word5:mouning,Word6:deu,foil:",
"word:tol,targetNonWord:gol,nOfSyllables:1,condition:Target-only,length:6,Word1:wodel,Word2:glimlilg,Word3:wuisderf,Word4:hoot,Word5:gol,Word6:blenk,foil:",
"word:bril,targetNonWord:slil,nOfSyllables:1,condition:Target-only,length:6,Word1:oorgeek,Word2:agbies,Word3:blijn,Word4:paldij,Word5:slil,Word6:loe,foil:",
"word:oor,targetNonWord:oop,nOfSyllables:1,condition:Target-only,length:6,Word1:roord,Word2:korg,Word3:boodsprop,Word4:woettaan,Word5:oop,Word6:klungan,foil:",
"word:touw,targetNonWord:tomp,nOfSyllables:1,condition:Target-only,length:6,Word1:oormoel,Word2:karp,Word3:retnin,Word4:alveid,Word5:tomp,Word6:penk,foil:",
"word:heks,targetNonWord:hoks,nOfSyllables:1,condition:Target-only,length:6,Word1:schieling,Word2:sprork,Word3:baarwuig,Word4:tat,Word5:hoks,Word6:loevas,foil:",
"word:bord,targetNonWord:bops,nOfSyllables:1,condition:Target+Foil,length:3,Word1:bolgwap,Word2:bops,Word3:ziep,Word4:,Word5:,Word6:,foil:bolgwap",
"word:aap,targetNonWord:ijp,nOfSyllables:1,condition:Target+Foil,length:3,Word1:ijnrorf,Word2:ijp,Word3:wuis,Word4:,Word5:,Word6:,foil:ijnrorf",
"word:vlieg,targetNonWord:vloeg,nOfSyllables:1,condition:Target+Foil,length:3,Word1:vloefpaak,Word2:vloeg,Word3:halp,Word4:,Word5:,Word6:,foil:vloefpaak",
"word:kast,targetNonWord:kang,nOfSyllables:1,condition:Target+Foil,length:3,Word1:kachboop,Word2:kang,Word3:vars,Word4:,Word5:,Word6:,foil:kachboop",
"word:brug,targetNonWord:tuch,nOfSyllables:1,condition:Target+Foil,length:3,Word1:tungbog,Word2:tuch,Word3:wag,Word4:,Word5:,Word6:,foil:tungbog",
"word:fles,targetNonWord:knes,nOfSyllables:1,condition:Target+Foil,length:3,Word1:knerwolp,Word2:knes,Word3:gops,Word4:,Word5:,Word6:,foil:knerwolp",
"word:mes,targetNonWord:mas,nOfSyllables:1,condition:Target+Foil,length:3,Word1:marmon,Word2:mas,Word3:niel,Word4:,Word5:,Word6:,foil:marmon",
"word:jas,targetNonWord:nas,nOfSyllables:1,condition:Target+Foil,length:3,Word1:nafpes,Word2:nas,Word3:roor ,Word4:,Word5:,Word6:,foil:nafpes",
"word:vis,targetNonWord:jis,nOfSyllables:1,condition:Target+Foil,length:3,Word1:jilgruik,Word2:jis,Word3:remp,Word4:,Word5:,Word6:,foil:jilgruik",
"word:voet,targetNonWord:vuit,nOfSyllables:1,condition:Target+Foil,length:3,Word1:vuikschoop,Word2:vuit,Word3:naf,Word4:,Word5:,Word6:,foil:vuikschoop",
"word:stoel,targetNonWord:stuil,nOfSyllables:1,condition:Target+Foil,length:3,Word1:stuindreek,Word2:stuil,Word3:keis,Word4:,Word5:,Word6:,foil:stuindreek",
"word:bom,targetNonWord:rom,nOfSyllables:1,condition:Target+Foil,length:3,Word1:rofreun,Word2:rom,Word3:zamp,Word4:,Word5:,Word6:,foil:rofreun",
"word:boom,targetNonWord:baam,nOfSyllables:1,condition:Target+Foil,length:3,Word1:baagfolp,Word2:baam,Word3:stid,Word4:,Word5:,Word6:,foil:baagfolp",
"word:trap,targetNonWord:zwap,nOfSyllables:1,condition:Target+Foil,length:3,Word1:zwantaar,Word2:zwap,Word3:heern,Word4:,Word5:,Word6:,foil:zwantaar",
"word:ring,targetNonWord:ling,nOfSyllables:1,condition:Target+Foil,length:3,Word1:lixkroei,Word2:ling,Word3:daul,Word4:,Word5:,Word6:,foil:lixkroei",
"word:dak,targetNonWord:nak,nOfSyllables:1,condition:Target+Foil,length:3,Word1:napbeig,Word2:nak,Word3:mel,Word4:,Word5:,Word6:,foil:napbeig",
"word:glas,targetNonWord:sjas,nOfSyllables:1,condition:Target+Foil,length:3,Word1:sjatmeep,Word2:sjas,Word3:voen,Word4:,Word5:,Word6:,foil:sjatmeep",
"word:bus,targetNonWord:bru,nOfSyllables:1,condition:Target+Foil,length:3,Word1:brozil,Word2:bru,Word3:zek,Word4:,Word5:,Word6:,foil:brozil",
"word:taart,targetNonWord:toort,nOfSyllables:1,condition:Target+Foil,length:4,Word1:toolgmong,Word2:toort,Word3:veepsel,Word4:sies,Word5:,Word6:,foil:toolgmong",
"word:muur,targetNonWord:scru,nOfSyllables:1,condition:Target+Foil,length:4,Word1:scriraal,Word2:scru,Word3:boekon,Word4:oes,Word5:,Word6:,foil:scriraal",
"word:broek,targetNonWord:groek,nOfSyllables:1,condition:Target+Foil,length:4,Word1:groedmiel,Word2:groek,Word3:voorwoer,Word4:ses,Word5:,Word6:,foil:groedmiel",
"word:oog,targetNonWord:ood,nOfSyllables:1,condition:Target+Foil,length:4,Word1:ooptaag,Word2:ood,Word3:vernee,Word4:krel,Word5:,Word6:,foil:ooptaag",
"word:brood,targetNonWord:bried,nOfSyllables:1,condition:Target+Foil,length:4,Word1:snes,Word2:briepkimp,Word3:bried,Word4:jutleen,Word5:,Word6:,foil:briepkimp",
"word:zon,targetNonWord:erm,nOfSyllables:1,condition:Target+Foil,length:4,Word1:kangoer,Word2:elgpaun,Word3:erm,Word4:mip,Word5:,Word6:,foil:elgpaun",
"word:neus,targetNonWord:kels,nOfSyllables:1,condition:Target+Foil,length:4,Word1:uitvong,Word2:kerplem,Word3:kels,Word4:pans,Word5:,Word6:,foil:kerplem",
"word:raam,targetNonWord:bap,nOfSyllables:1,condition:Target+Foil,length:4,Word1:woors,Word2:bandars,Word3:bap,Word4:olvin,Word5:,Word6:,foil:bandars",
"word:trein,targetNonWord:paaks,nOfSyllables:1,condition:Target+Foil,length:4,Word1:ner,Word2:paandvelm,Word3:paaks,Word4:pernijn,Word5:,Word6:,foil:paandvelm",
"word:hoed,targetNonWord:koed,nOfSyllables:1,condition:Target+Foil,length:4,Word1:koegpaat,Word2:momp,Word3:koed,Word4:noger,Word5:,Word6:,foil:koegpaat",
"word:blik,targetNonWord:drik,nOfSyllables:1,condition:Target+Foil,length:4,Word1:dritmeek,Word2:stetjel,Word3:drik,Word4:tar ,Word5:,Word6:,foil:dritmeek",
"word:arm,targetNonWord:von,nOfSyllables:1,condition:Target+Foil,length:4,Word1:vormerp,Word2:moen,Word3:von,Word4:merbog,Word5:,Word6:,foil:vormerp",
"word:kerk,targetNonWord:nerg,nOfSyllables:1,condition:Target+Foil,length:4,Word1:nelktoes,Word2:smoek,Word3:nerg,Word4:larnies,Word5:,Word6:,foil:nelktoes",
"word:bal,targetNonWord:laam,nOfSyllables:1,condition:Target+Foil,length:4,Word1:laakbuim,Word2:staks,Word3:laam,Word4:scheennoon,Word5:,Word6:,foil:laakbuim",
"word:paard,targetNonWord:slein,nOfSyllables:1,condition:Target+Foil,length:4,Word1:sleitsog,Word2:toebong,Word3:slein,Word4:luif,Word5:,Word6:,foil:sleitsog",
"word:bank,targetNonWord:benk,nOfSyllables:1,condition:Target+Foil,length:4,Word1:belfnast,Word2:akkum,Word3:benk,Word4:vag,Word5:,Word6:,foil:belfnast",
"word:boot,targetNonWord:book,nOfSyllables:1,condition:Target+Foil,length:4,Word1:boopdijs,Word2:olburcht,Word3:book,Word4:gip,Word5:,Word6:,foil:boopdijs",
"word:zak,targetNonWord:zik,nOfSyllables:1,condition:Target+Foil,length:4,Word1:zifknil,Word2:rar,Word3:zik,Word4:olmeer,Word5:,Word6:,foil:zifknil",
"word:vuur,targetNonWord:fjon,nOfSyllables:1,condition:Target+Foil,length:5,Word1:fjodschelg,Word2:fjon,Word3:wisdaag,Word4:tuik,Word5:poks,Word6:,foil:fjodschelg",
"word:kip,targetNonWord:kep,nOfSyllables:1,condition:Target+Foil,length:5,Word1:vui,Word2:kekmieg,Word3:kep,Word4:peek,Word5:tukliek,Word6:,foil:kekmieg",
"word:hoef,targetNonWord:hogt,nOfSyllables:1,condition:Target+Foil,length:5,Word1:ontpad,Word2:holmdrins,Word3:hogt,Word4:toor,Word5:roog,Word6:,foil:holmdrins",
"word:stuur,targetNonWord:hies,nOfSyllables:1,condition:Target+Foil,length:5,Word1:vaatlal,Word2:nos,Word3:hiemrief,Word4:hies,Word5:fots,Word6:,foil:hiemrief",
"word:boek,targetNonWord:zan,nOfSyllables:1,condition:Target+Foil,length:5,Word1:dauk,Word2:andoer,Word3:zallalk,Word4:zan,Word5:slon,Word6:,foil:zallalk",
"word:doos,targetNonWord:duis,nOfSyllables:1,condition:Target+Foil,length:5,Word1:duigjooi,Word2:fruik,Word3:duis,Word4:eels,Word5:apder,Word6:,foil:duigjooi",
"word:hond,targetNonWord:ked,nOfSyllables:1,condition:Target+Foil,length:5,Word1:kergeuk,Word2:vierlan,Word3:ked,Word4:dif,Word5:volp,Word6:,foil:kergeuk",
"word:hart,targetNonWord:teur,nOfSyllables:1,condition:Target+Foil,length:5,Word1:teumsnaf,Word2:hyk,Word3:teur,Word4:geegheid,Word5:dorts,Word6:,foil:teumsnaf",
"word:hand,targetNonWord:kem,nOfSyllables:1,condition:Target+Foil,length:5,Word1:guil,Word2:kedlim,Word3:sorbuin,Word4:kem,Word5:vep,Word6:,foil:kedlim",
"word:bed,targetNonWord:zarp,nOfSyllables:1,condition:Target+Foil,length:5,Word1:vleek,Word2:zanskolm,Word3:kelf,Word4:zarp,Word5:bolpes,Word6:,foil:zanskolm",
"word:deur,targetNonWord:koef,nOfSyllables:1,condition:Target+Foil,length:5,Word1:raandog,Word2:koepteik,Word3:nocht,Word4:koef,Word5:womp,Word6:,foil:koepteik",
"word:tent,targetNonWord:teng,nOfSyllables:1,condition:Target+Foil,length:5,Word1:texbuif,Word2:moop,Word3:faan,Word4:teng,Word5:zajukt,Word6:,foil:texbuif",
"word:huis,targetNonWord:chlon,nOfSyllables:1,condition:Target+Foil,length:5,Word1:chlokhien,Word2:doon,Word3:keeg,Word4:chlon,Word5:vijnwel,Word6:,foil:chlokhien",
"word:man,targetNonWord:bauk,nOfSyllables:1,condition:Target+Foil,length:5,Word1:bauswor,Word2:aaks,Word3:paldur,Word4:bauk,Word5:schreerp,Word6:,foil:bauswor",
"word:kom,targetNonWord:hats,nOfSyllables:1,condition:Target+Foil,length:5,Word1:halgherm,Word2:badsies,Word3:goos,Word4:hats,Word5:traap,Word6:,foil:halgherm",
"word:zalf,targetNonWord:haps,nOfSyllables:1,condition:Target+Foil,length:5,Word1:harfbijg,Word2:gruif,Word3:naaglot,Word4:haps,Word5:juit,Word6:,foil:harfbijg",
"word:trouw,targetNonWord:trops,nOfSyllables:1,condition:Target+Foil,length:5,Word1:trolkdoef,Word2:weepbuis,Word3:kogs,Word4:trops,Word5:waaf,Word6:,foil:trolkdoef",
"word:maan,targetNonWord:maap,nOfSyllables:1,condition:Target+Foil,length:6,Word1:maafnoep,Word2:maap,Word3:rargen,Word4:kons,Word5:wop,Word6:reveer,foil:maafnoep",
"word:velg,targetNonWord:duil,nOfSyllables:1,condition:Target+Foil,length:6,Word1:gangkeer,Word2:duiskalp,Word3:duil,Word4:opvek,Word5:jeel,Word6:snaag,foil:duiskalp",
"word:streep,targetNonWord:wuik,nOfSyllables:1,condition:Target+Foil,length:6,Word1:lendaar,Word2:grem,Word3:wuigkroer,Word4:wuik,Word5:koereek,Word6:kork,foil:wuigkroer",
"word:paars,targetNonWord:breeg,nOfSyllables:1,condition:Target+Foil,length:6,Word1:hoortbijn,Word2:zel,Word3:grubond,Word4:breelmeeg,Word5:breeg,Word6:scherg,foil:breelmeeg",
"word:gans,targetNonWord:gret,nOfSyllables:1,condition:Target+Foil,length:6,Word1:gremdoep,Word2:snuim,Word3:gret,Word4:wuil,Word5:warnis,Word6:winkheek,foil:gremdoep",
"word:kuil,targetNonWord:baust,nOfSyllables:1,condition:Target+Foil,length:6,Word1:baaf,Word2:baundleu,Word3:foestvag,Word4:baust,Word5:tan,Word6:rornas,foil:baundleu",
"word:bad,targetNonWord:bam,nOfSyllables:1,condition:Target+Foil,length:6,Word1:wirums,Word2:mefdel,Word3:bafruip,Word4:lir,Word5:bam,Word6:lank,foil:bafruip",
"word:klas,targetNonWord:roen,nOfSyllables:1,condition:Target+Foil,length:6,Word1:zeut,Word2:glank,Word3:roegtaus,Word4:lentar,Word5:roen,Word6:rielak,foil:roegtaus",
"word:grot,targetNonWord:vlaad,nOfSyllables:1,condition:Target+Foil,length:6,Word1:vlaasrig,Word2:kalvoon,Word3:voornil,Word4:vlaad,Word5:bruip,Word6:bax,foil:vlaasrig",
"word:buik,targetNonWord:veus,nOfSyllables:1,condition:Target+Foil,length:6,Word1:veuphalk,Word2:ollusk,Word3:gaam,Word4:veus,Word5:ijn,Word6:zeiming,foil:veuphalk",
"word:beest,targetNonWord:klag,nOfSyllables:1,condition:Target+Foil,length:6,Word1:aalpeis,Word2:klanwuist,Word3:sjoek,Word4:snerm,Word5:klag,Word6:arrui,foil:klanwuist",
"word:vloed,targetNonWord:pras,nOfSyllables:1,condition:Target+Foil,length:6,Word1:kroen,Word2:prambeup,Word3:sidraal,Word4:beuting,Word5:pras,Word6:relp,foil:prambeup",
"word:ster,targetNonWord:krer,nOfSyllables:1,condition:Target+Foil,length:6,Word1:kremgof,Word2:pef,Word3:monksel,Word4:muig,Word5:krer,Word6:deper,foil:kremgof",
"word:steeg,targetNonWord:strijp,nOfSyllables:1,condition:Target+Foil,length:6,Word1:strijmrin,Word2:doog,Word3:handreer,Word4:zordoer,Word5:strijp,Word6:sleer,foil:strijmrin",
"word:zoen,targetNonWord:poers,nOfSyllables:1,condition:Target+Foil,length:6,Word1:poentflins,Word2:uitmed,Word3:baag,Word4:vir,Word5:poers,Word6:ierwofs,foil:poentflins",
"word:klad,targetNonWord:gars,nOfSyllables:1,condition:Target+Foil,length:6,Word1:galtvits,Word2:raan,Word3:seipoon,Word4:baaps,Word5:gars,Word6:aanmed,foil:galtvits",
"word:jaar,targetNonWord:jaaf,nOfSyllables:1,condition:Target+Foil,length:6,Word1:jaadmers,Word2:lijngaals,Word3:kral,Word4:vammoer,Word5:jaaf,Word6:spool,foil:jaadmers",
"word:loep,targetNonWord:luip,nOfSyllables:1,condition:NoTarget,length:3,Word1:kleis,Word2:heerting,Word3:zwins,Word4:,Word5:,Word6:,foil:",
"word:doof,targetNonWord:moof,nOfSyllables:1,condition:NoTarget,length:3,Word1:zolp,Word2:heeg,Word3:jasween,Word4:,Word5:,Word6:,foil:",
"word:nier,targetNonWord:rier,nOfSyllables:1,condition:NoTarget,length:3,Word1:zuif,Word2:voormool,Word3:slig,Word4:,Word5:,Word6:,foil:",
"word:schuim,targetNonWord:schijm,nOfSyllables:1,condition:NoTarget,length:3,Word1:amnaar,Word2:woe,Word3:trar,Word4:,Word5:,Word6:,foil:",
"word:stift,targetNonWord:stins,nOfSyllables:1,condition:NoTarget,length:3,Word1:prok,Word2:din,Word3:rieding,Word4:,Word5:,Word6:,foil:",
"word:tong,targetNonWord:tonk,nOfSyllables:1,condition:NoTarget,length:3,Word1:zandog,Word2:dijg,Word3:vets,Word4:,Word5:,Word6:,foil:",
"word:roer,targetNonWord:doer,nOfSyllables:1,condition:NoTarget,length:3,Word1:staas,Word2:uitbag,Word3:maars,Word4:,Word5:,Word6:,foil:",
"word:moord,targetNonWord:moops,nOfSyllables:1,condition:NoTarget,length:4,Word1:fluik,Word2:ontseet,Word3:hook,Word4:gebeeg,Word5:,Word6:,foil:",
"word:baas,targetNonWord:baap,nOfSyllables:1,condition:NoTarget,length:4,Word1:rer,Word2:bem,Word3:foersmaal,Word4:dadroek,Word5:,Word6:,foil:",
"word:poot,targetNonWord:peit,nOfSyllables:1,condition:NoTarget,length:4,Word1:nal,Word2:guiping,Word3:buip,Word4:herbing,Word5:,Word6:,foil:",
"word:blaar,targetNonWord:slaar,nOfSyllables:1,condition:NoTarget,length:4,Word1:naags,Word2:onliel,Word3:zaklaak,Word4:raf,Word5:,Word6:,foil:",
"word:doek,targetNonWord:deek,nOfSyllables:1,condition:NoTarget,length:4,Word1:eerkuid,Word2:jor,Word3:vas,Word4:wijtoeg,Word5:,Word6:,foil:",
"word:wand,targetNonWord:wamp,nOfSyllables:1,condition:NoTarget,length:4,Word1:aanmil,Word2:wons,Word3:toezol,Word4:fap,Word5:,Word6:,foil:",
"word:pop,targetNonWord:lop,nOfSyllables:1,condition:NoTarget,length:4,Word1:voorserm,Word2:muiland,Word3:fraal,Word4:kijn,Word5:,Word6:,foil:",
"word:vocht,targetNonWord:gocht,nOfSyllables:1,condition:NoTarget,length:5,Word1:inbong,Word2:gop,Word3:dorm,Word4:wiffer,Word5:blem,Word6:,foil:",
"word:wet,targetNonWord:wot,nOfSyllables:1,condition:NoTarget,length:5,Word1:bijs,Word2:stror,Word3:spen,Word4:taapman,Word5:piktoor,Word6:,foil:",
"word:troon,targetNonWord:groon,nOfSyllables:1,condition:NoTarget,length:5,Word1:woos,Word2:aanbees,Word3:stiem,Word4:roon,Word5:gardeen,Word6:,foil:",
"word:roos,targetNonWord:ries,nOfSyllables:1,condition:NoTarget,length:5,Word1:kreen,Word2:omrong,Word3:aannok,Word4:toots,Word5:klil,Word6:,foil:",
"word:broer,targetNonWord:troer,nOfSyllables:1,condition:NoTarget,length:5,Word1:voortegt,Word2:brof,Word3:blook,Word4:spaag,Word5:afbuip,Word6:,foil:",
"word:blaas,targetNonWord:draas,nOfSyllables:1,condition:NoTarget,length:5,Word1:aanbag,Word2:smap,Word3:tetjel,Word4:gog,Word5:pag,Word6:,foil:",
"word:vet,targetNonWord:vek,nOfSyllables:1,condition:NoTarget,length:5,Word1:vank,Word2:linier,Word3:varn,Word4:lorte,Word5:gruid,Word6:,foil:",
"word:krans,targetNonWord:krons,nOfSyllables:1,condition:NoTarget,length:6,Word1:milfoon,Word2:wiks,Word3:braal,Word4:palfzer,Word5:kijder,Word6:grui ,foil:",
"word:cel,targetNonWord:woen,nOfSyllables:1,condition:NoTarget,length:6,Word1:kaans,Word2:noet,Word3:woger,Word4:spaper,Word5:zook,Word6:tanel,foil:",
"word:bloed,targetNonWord:zwoed,nOfSyllables:1,condition:NoTarget,length:6,Word1:liem,Word2:watse,Word3:kieg,Word4:firp,Word5:bioel,Word6:gebog,foil:",
"word:hoek,targetNonWord:hauk,nOfSyllables:1,condition:NoTarget,length:6,Word1:dipon,Word2:krets,Word3:rahel,Word4:noek,Word5:ronoen,Word6:druid,foil:",
"word:boer,targetNonWord:goer,nOfSyllables:1,condition:NoTarget,length:6,Word1:uik,Word2:tolas,Word3:gepij,Word4:lanhaap,Word5:vres,Word6:grank,foil:",
"word:grens,targetNonWord:spens,nOfSyllables:1,condition:NoTarget,length:6,Word1:oening,Word2:zilms,Word3:lits,Word4:kietsoor,Word5:huipoord,Word6:zimp,foil:",
"word:knop,targetNonWord:smop,nOfSyllables:1,condition:NoTarget,length:6,Word1:loenak,Word2:wandstrap,Word3:ples,Word4:liel,Word5:jeen,Word6:vergpuis,foil:",
};
}
