/*
 * Copyright (C) 2018 Max Planck Institute for Psycholinguistics, Nijmegen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.frinex.adaptivevocabularyassessment.client.service.advocaspool;

/**
 *
 * @author olhshk
 */
public class NonWords_HUN_round_1 extends CsvStringWrapper {

    public NonWords_HUN_round_1() {
        this.CSV_STRING = "Spelling\n"
                + "szeudor\n"
                + "hézhet\n"
                + "pirigari\n"
                + "úszamos\n"
                + "gyalaha\n"
                + "felte\n"
                + "gyant\n"
                + "barlódiurné\n"
                + "anyargany\n"
                + "pikusz\n"
                + "maszt\n"
                + "erődéki\n"
                + "hormati\n"
                + "ószeven\n"
                + "gramoszi\n"
                + "konfirki\n"
                + "inta\n"
                + "antgathat\n"
                + "vényegő\n"
                + "attyűködő\n"
                + "skadai\n"
                + "lublika\n"
                + "zajkottsi\n"
                + "egant\n"
                + "szethetősi\n"
                + "felján\n"
                + "alárdonos\n"
                + "reztetély\n"
                + "aurult\n"
                + "invonult\n"
                + "nyolgató\n"
                + "gyenkedéri\n"
                + "hozandzsa\n"
                + "gágy\n"
                + "leverzsköl\n"
                + "alka\n"
                + "zökkévei\n"
                + "késetetély\n"
                + "takorák\n"
                + "estilágítő\n"
                + "khiba\n"
                + "trikarítés\n"
                + "léptelegy\n"
                + "petkerhet\n"
                + "ponyai\n"
                + "amoz\n"
                + "márossálha\n"
                + "növetlenső\n"
                + "heltetett\n"
                + "pirodáló\n"
                + "kajakusz\n"
                + "törvosítoz\n"
                + "viszt\n"
                + "posdótelő\n"
                + "tilitálós\n"
                + "többhagyos\n"
                + "cselens\n"
                + "katerült\n"
                + "maximax\n"
                + "villi\n"
                + "kántitált\n"
                + "tamia\n"
                + "aprimitmus\n"
                + "hendesen\n"
                + "tortya\n"
                + "kelől\n"
                + "kendőr\n"
                + "keltos\n"
                + "tojászköl\n"
                + "kibeti\n"
                + "hunfai\n"
                + "kiskolható\n"
                + "alanító\n"
                + "altet\n"
                + "orvatható\n"
                + "vetézmés\n"
                + "pósfalmár\n"
                + "kocskesi\n"
                + "ponálgai\n"
                + "vonzum\n"
                + "abeti\n"
                + "fartózható\n"
                + "bámérő\n"
                + "ultatlados\n"
                + "őrint\n"
                + "mihálóz\n"
                + "sivirányi\n"
                + "víker\n"
                + "keritkol\n"
                + "krákfai\n"
                + "nyurcaret\n"
                + "terpad\n"
                + "stíluszirt\n"
                + "karnogó\n"
                + "nyolcsolat\n"
                + "illikázó\n"
                + "recialice\n"
                + "hider\n"
                + "antra\n"
                + "cséltás\n"
                + "lábtörög\n"
                + "szichosol\n"
                + "szimboló\n"
                + "frisáles\n"
                + "gádosíthat\n"
                + "főcsemő\n"
                + "csomozdoni\n"
                + "tévedzik\n"
                + "rozintem\n"
                + "parkkói\n"
                + "megköny\n"
                + "átütésetti\n"
                + "borodó\n"
                + "meggyabb\n"
                + "tartáló\n"
                + "alsokfejű\n"
                + "balmozáraz\n"
                + "gyásos\n"
                + "sakat\n"
                + "dofízissed\n"
                + "nyagy\n"
                + "kijjongó\n"
                + "lező\n"
                + "megpadék\n"
                + "kilukát";
    }
}
