/*
 * Copyright (C) 2018 Max Planck Institute for Psycholinguistics, Nijmegen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.frinex.adaptivevocabularyassessment.client.service.advocaspool;

/**
 *
 * @author olhshk
 */
public class NonWords_HUN_round_2 extends CsvStringWrapper {

    public NonWords_HUN_round_2() {
        this.CSV_STRING = "Spelling\n"
                + "stalp\n"
                + "szelégül\n"
                + "összalaj\n"
                + "cirózó\n"
                + "legyszekli\n"
                + "borhátsz\n"
                + "lazarjadó\n"
                + "ellagcse\n"
                + "rohangsári\n"
                + "isminchegy\n"
                + "falvangú\n"
                + "sűrítható\n"
                + "kilolvai\n"
                + "aragas\n"
                + "legiző\n"
                + "ocsikáltó\n"
                + "avonaliba\n"
                + "kosi\n"
                + "látolt\n"
                + "vágárd\n"
                + "stasassző\n"
                + "vároló\n"
                + "felezéri\n"
                + "engelétei\n"
                + "perilita\n"
                + "salógázó\n"
                + "prografej\n"
                + "keszködmön\n"
                + "sulás\n"
                + "majozárói\n"
                + "visszín\n"
                + "indezget\n"
                + "ernyak\n"
                + "felmi\n"
                + "nőttetett\n"
                + "kétikussi\n"
                + "extuál\n"
                + "kvacsvagos\n"
                + "balji\n"
                + "tutamizál\n"
                + "tajtásos\n"
                + "vésségi\n"
                + "tánló\n"
                + "retta\n"
                + "talauzik\n"
                + "vilálható\n"
                + "bakú\n"
                + "nyilváram\n"
                + "méresedik\n"
                + "ügyenlősi\n"
                + "antyúzható\n"
                + "daragasi\n"
                + "novagár\n"
                + "szigon\n"
                + "lemesség\n"
                + "storka\n"
                + "dohorpák\n"
                + "zomás\n"
                + "garn\n"
                + "bolyodás\n"
                + "csüggöny\n"
                + "jegedény\n"
                + "oldalmi\n"
                + "konyosbetű\n"
                + "érkésztás\n"
                + "csenyei\n"
                + "kiletette\n"
                + "dokozotty\n"
                + "aximai\n"
                + "tröshet\n"
                + "nagyarnák\n"
                + "végregura\n"
                + "suszi\n"
                + "ködik\n"
                + "kíványozhat\n"
                + "méhezter\n"
                + "tiszogó\n"
                + "néghajóti\n"
                + "dumcsoska\n"
                + "almattoló\n"
                + "storítő\n"
                + "szivalka\n"
                + "gyóka\n"
                + "pozákevegy\n"
                + "maliző\n"
                + "priváló\n"
                + "egellendő\n"
                + "spratika\n"
                + "sételi\n"
                + "szöngő\n"
                + "szabotró\n"
                + "zentiekert\n"
                + "oldolt\n"
                + "puharmes\n"
                + "tömzsa\n"
                + "pentez\n"
                + "fekcionák\n"
                + "tárcsöngy\n"
                + "cigazodox\n"
                + "teszű\n"
                + "balassol\n"
                + "kunyai\n"
                + "bolos\n"
                + "likálható\n"
                + "grancs\n"
                + "hitódó\n"
                + "sikációzan\n"
                + "alukandós\n"
                + "elikázható\n"
                + "anaszsében\n"
                + "retálhit\n"
                + "vicsadomás\n"
                + "konyrúd\n"
                + "norvend\n"
                + "zomogyi\n"
                + "arló\n"
                + "renderzia\n"
                + "rosítottsi\n"
                + "kontlás\n"
                + "tömődékhet\n"
                + "lecskediriz\n"
                + "illatlansz\n"
                + "esztikussz\n"
                + "majánosol\n"
                + "boldódi";
    }
}
