/*
 * Copyright (C) 2018 Max Planck Institute for Psycholinguistics, Nijmegen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place  min Suite 330, Boston, MA  02111 min1307, USA.
 */
package nl.mpi.tg.eg.frinex.adaptivevocabularyassessment.client.service.lexicaldecision;

/**
 *
 * @author olhshk
 */
public class LexicalDecisionCsv {

    public static String CSV_STIMULI = "Trial_Nr;condition;word;frequency;wav;expected;length\n"
            + "0,1;practice;bek;high;bek.wav;M;3\n"
            + "0,2;practice;bun;NA;bun.wav;Z;3\n"
            + "0,3;practice;vor;NA;vor.wav;Z;3\n"
            + "1;exp;geschenk;high;geschenk.wav;M;8\n"
            + "2;exp;gesp;low;gesp.wav;M;4\n"
            + "3;exp;schars;NA;schars.wav;Z;6\n"
            + "4;exp;kever;low;kever.wav;M;5\n"
            + "5;exp;gedijgte;NA;gedijgte.wav;Z;8\n"
            + "6;exp;microfoon;high;microfoon.wav;M;9\n"
            + "7;exp;voetbal;high;voetbal.wav;M;7\n"
            + "8;exp;kolm;NA;kolm.wav;Z;4\n"
            + "9;exp;raket;high;raket.wav;M;5\n"
            + "10;exp;gelg;NA;gelg.wav;Z;4\n"
            + "11;exp;vlees;high;vlees.wav;M;5\n"
            + "12;exp;mavel;NA;mavel.wav;Z;5\n"
            + "13;exp;kollanje;NA;kollanje.wav;Z;8\n"
            + "14;exp;auto;high;auto.wav;M;4\n"
            + "15;exp;kegel;low;kegel.wav;M;5\n"
            + "16;exp;droksem;NA;droksem.wav;Z;7\n"
            + "17;exp;postiel;NA;postiel.wav;Z;7\n"
            + "18;exp;magneet;low;magneet.wav;M;7\n"
            + "19;exp;gral;NA;gral.wav;Z;4\n"
            + "20;exp;doorn;low;doorn.wav;M;5\n"
            + "21;exp;letel;NA;letel.wav;Z;5\n"
            + "22;exp;daarn;NA;daarn.wav;Z;5\n"
            + "23;exp;scherm;high;scherm.wav;M;6\n"
            + "24;exp;vlijs;NA;vlijs.wav;Z;5\n"
            + "25;exp;halg;NA;halg.wav;Z;4\n"
            + "26;exp;marmot;low;marmot.wav;M;6\n"
            + "27;exp;papier;high;papier.wav;M;6\n"
            + "28;exp;lard;NA;lard.wav;Z;4\n"
            + "29;exp;gebouw;high;gebouw.wav;M;6\n"
            + "30;exp;gebamp;NA;gebamp.wav;Z;6\n"
            + "31;exp;professor;high;professor.wav;M;9\n"
            + "32;exp;vril;NA;vril.wav;Z;4\n"
            + "33;exp;brein;high;brein.wav;M;5\n"
            + "34;exp;korf;low;korf.wav;M;4\n"
            + "35;exp;geschork;NA;geschork.wav;Z;8\n"
            + "36;exp;gong;low;gong.wav;M;4\n"
            + "37;exp;peeuw;NA;peeuw.wav;Z;5\n"
            + "38;exp;kruis;high;kruis.wav;M;5\n"
            + "39;exp;geraamte;low;geraamte.wav;M;8\n"
            + "40;exp;palmus;NA;palmus.wav;Z;6\n"
            + "41;exp;schebes;NA;schebes.wav;Z;7\n"
            + "42;exp;gitaar;high;gitaar.wav;M;6\n"
            + "43;exp;schelg;NA;schelg.wav;Z;6\n"
            + "44;exp;hagel;low;hagel.wav;M;5\n"
            + "45;exp;gromp;NA;gromp.wav;Z;5\n"
            + "46;exp;panoer;NA;panoer.wav;Z;6\n"
            + "47;exp;vijg;low;vijg.wav;M;4\n"
            + "48;exp;gralinek;NA;gralinek.wav;Z;8\n"
            + "49;exp;leeuw;high;leeuw.wav;M;5\n"
            + "50;exp;pantoffel;low;pantoffel.wav;M;9\n"
            + "51;exp;bitier;NA;bitier.wav;Z;6\n"
            + "52;exp;televisie;high;televisie.wav;M;9\n"
            + "53;exp;soldaat;high;soldaat.wav;M;7\n"
            + "54;exp;ropaan;NA;ropaan.wav;Z;6\n"
            + "55;exp;quosirade;NA;quosirade.wav;Z;9\n"
            + "56;exp;ambtenaar;low;ambtenaar.wav;M;9\n"
            + "57;exp;zindi;NA;zindi.wav;Z;5\n"
            + "58;exp;huig;low;huig.wav;M;4\n"
            + "59;exp;auli;NA;auli.wav;Z;4\n"
            + "60;exp;aardbei;low;aardbei.wav;M;7\n"
            + "61;exp;smaai;NA;smaai.wav;Z;5\n"
            + "62;exp;chocolade;high;chocolade.wav;M;9\n"
            + "63;exp;schemer;low;schemer.wav;M;7\n"
            + "64;exp;jillo;NA;jillo.wav;Z;5\n"
            + "65;exp;terekapie;NA;terekapie.wav;Z;9\n"
            + "66;exp;bijbel;high;bijbel.wav;M;6\n"
            + "67;exp;bliksem;high;bliksem.wav;M;7\n"
            + "68;exp;lieuw;NA;lieuw.wav;Z;5\n"
            + "69;exp;aardloe;NA;aardloe.wav;Z;7\n"
            + "70;exp;sauna;low;sauna.wav;M;5\n"
            + "71;exp;hepel;NA;hepel.wav;Z;5\n"
            + "72;exp;vlaai;low;vlaai.wav;M;5\n"
            + "73;exp;miklohien;NA;miklohien.wav;Z;9\n"
            + "74;exp;jager;high;jager.wav;M;5\n"
            + "75;exp;pebza;NA;pebza.wav;Z;5\n"
            + "76;exp;zwoem;NA;zwoem.wav;Z;5\n"
            + "77;exp;pedaal;low;pedaal.wav;M;6\n"
            + "78;exp;madveet;NA;madveet.wav;Z;7\n"
            + "79;exp;lamp;high;lamp.wav;M;4\n"
            + "80;exp;sardaat;NA;sardaat.wav;Z;7\n"
            + "81;exp;haver;low;haver.wav;M;5\n"
            + "82;exp;treik;NA;treik.wav;Z;5\n"
            + "83;exp;hark;low;hark.wav;M;4\n"
            + "84;exp;kasteel;high;kasteel.wav;M;7\n"
            + "85;exp;marbit;NA;marbit.wav;Z;6\n"
            + "86;exp;smes;NA;smes.wav;Z;4\n"
            + "87;exp;schors;low;schors.wav;M;6\n"
            + "88;exp;boevel;NA;boevel.wav;Z;6\n"
            + "89;exp;klarinet;low;klarinet.wav;M;8\n"
            + "90;exp;anktekier;NA;anktekier.wav;Z;9\n"
            + "91;exp;trein;high;trein.wav;M;5\n"
            + "92;exp;gork;NA;gork.wav;Z;4\n"
            + "93;exp;veter;low;veter.wav;M;5\n"
            + "94;exp;mastiel;NA;mastiel.wav;Z;7\n"
            + "95;exp;vliemkuig;NA;vliemkuig.wav;Z;9\n"
            + "96;exp;rozijn;low;rozijn.wav;M;6\n"
            + "97;exp;kuig;NA;kuig.wav;Z;4\n"
            + "98;exp;gras;high;gras.wav;M;4\n"
            + "99;exp;mazer;NA;mazer.wav;Z;5\n"
            + "100;exp;bloem;high;bloem.wav;M;5\n"
            + "101;exp;rapek;NA;rapek.wav;Z;5\n"
            + "102;exp;fles;high;fles.wav;M;4\n"
            + "103;exp;meeuw;low;meeuw.wav;M;5\n"
            + "104;exp;kries;NA;kries.wav;Z;5\n"
            + "105;exp;pistool;high;pistool.wav;M;7\n"
            + "106;exp;parfum;high;parfum.wav;M;6\n"
            + "107;exp;grader;NA;grader.wav;Z;6\n"
            + "108;exp;klomp;low;klomp.wav;M;5\n"
            + "109;exp;vaatlal;NA;vaatlal.wav;Z;7\n"
            + "110;exp;bril;high;bril.wav;M;4\n"
            + "111;exp;cello;low;cello.wav;M;5\n"
            + "112;exp;periel;NA;periel.wav;Z;6\n"
            + "113;exp;brien;NA;brien.wav;Z;5\n"
            + "114;exp;pizza;high;pizza.wav;M;5\n"
            + "115;exp;faver;NA;faver.wav;Z;5\n"
            + "116;exp;kastanje;low;kastanje.wav;M;8\n"
            + "117;exp;dijg;NA;dijg.wav;Z;4\n"
            + "118;exp;reber;NA;reber.wav;Z;5\n"
            + "119;exp;krater;low;krater.wav;M;6\n"
            + "120;exp;pantabbel;NA;pantabbel.wav;Z;9";
}
