/*
 * Copyright (C) 2019 Max Planck Institute for Psycholinguistics, Nijmegen
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package nl.mpi.tg.eg.frinex.adaptivevocabularyassessment.client.service.konopkapool;

/**
 *
 * @author olhshk
 */
public class KonopkaCsv {

    public static String CSV_STRING = "Nr;Item;Condition;(Patient_)inanimate_animal_human;Location_agent;Picture\n"
            + "1;The man is fishing;Filler;3;na;fishing.png\n"
            + "2;The man is planting the tree;Active;1;left;man_planting_tree3L.png\n"
            + "3;The dwarf laughs;Filler;3;na;dwarf.png\n"
            + "4;The mayor (man) is unveiling the vase;Active;1;left;mayor_unveiling_vaseL.png\n"
            + "5;The boy jumps off the rock;Filler;3;na;boy_jumping_off_rock_T.png\n"
            + "6;The horse is kicking the farmer;Passive;3;right;horse_kicking_farmerR\n"
            + "7;The woman puts on her make-up;Filler;3;na;makeup3.png\n"
            + "8;The detective found the gun;Active;1;left;detective_finding_gunL.png\n"
            + "9;The girl is sleeping;Filler;3;na;girlsleeping.png\n"
            + "10;The frog caught a fly;Active;2;right;frog_catching_flyR.png\n"
            + "11;The boy is swinging;Filler;3;na;swinging2.png\n"
            + "12;The policeman arrested a man/boy;Passive;3;left;cop_arresting_man2L.png\n"
            + "13;The girl is weaving;Filler;3;na;weaving.png\n"
            + "14;The doctor washed the baby;Passive;3;right;doctor_washing_baby2R.png\n"
            + "15;The saddle lies on the fence;Filler;1;na;saddle.png\n"
            + "16;The man is lifting the bench;Active;1;left;man_lifting_benchL.png\n"
            + "17;The boy is writing;Filler;3;na;student.png\n"
            + "18;The journalist is interviewing an actor;Passive;3;right;journalist_interviewing_actor2R.png\n"
            + "19;The man is smoking;Filler;3;na;man_smoking.png\n"
            + "20;The girl is taking the cookies;Active;1;right;girl_taking_cookiesR.png\n"
            + "21;The witch is flying on a broomstick;Filler;3;na;witch.png\n"
            + "22;The punk sprayed the fence;Active;1;left;punk_spraying_fence2L.png\n"
            + "23;The man is shivering;Filler;3;na;shivering2.png\n"
            + "24;The girl is tickling the boy;Passive;3;left;girl_tickling_boy2L.png\n"
            + "25;The woman brushes her teeth;Filler;3;na;brushingteeth.png\n"
            + "26;The man is pushing the bed;Passive;1;right;man_pushing_bed2R.png\n"
            + "27;The dog is lying on his back;Filler;2;na;dog_lying_on_back2_T.png\n"
            + "28;The boyscout is roasting a pig;Active;2;right;boyscout_roasting_pigR.png\n"
            + "29;The snowman is melting;Filler;1;na;snowman2.png\n"
            + "30;The shark is eating/swallowing a man;Passive;3;left;shark_swallowing_man2L.png\n"
            + "31;The man takes a shower;Filler;3;na;man_under_shower.png\n"
            + "32;Santa Claus is dragging the Christmas tree;Active;1;right;santa_dragging_treeR.png\n"
            + "33;The man and woman are rowing;Filler;3;na;rowing.png\n"
            + "34;The bride is cutting the cake;Active;1;left;bride_cutting_cakeL.png\n"
            + "35;The woman is roller skating;Filler;3;na;rollerskating.png\n"
            + "36;The bee is stinging the man;Passive;3;right;bee_stinging_manR.png\n"
            + "37;The couple is dancing;Filler;3;na;coupledancing.png\n"
            + "38;The professor is congratulating the student;Passive;3;left;professor_congratulating_studentL.png\n"
            + "39;The house is on fire;Filler;1;na;housefire.png\n"
            + "40;The burglar smashed the window;Active;1;right;burglar_smashing_window3R.png\n"
            + "41;The man is leaning against a cart;Filler;3;left;man_leaning_against_cartL_T.png\n"
            + "42;The bulldozer destroyed the building;Passive;1;right;bulldozerR.png\n"
            + "43;The actor bows;Filler;3;na;actor.png\n"
            + "44;The old woman is mopping the stairs;Active;1;left;woman_mopping_stairsL.png\n"
            + "45;The wolf is howling;Filler;2;na;wolf.png\n"
            + "46;The mechanic is fixing the car;Passive;1;left;mechanic_fixing_car4L.png\n"
            + "47;The girl is sliding down;Filler;3;na;slide.png\n"
            + "48;The helicopter is pulling the diver out of the water;Passive;3;right;helicopter_pulling_diver_out_of_waterR.png\n"
            + "49;The boy raises his hand;Filler;3;na;raisinghand.png\n"
            + "50;The man is pulling the donkey;Active;2;right;farmer_pulling_donkeyR.png\n"
            + "51;The woman is sewing;Filler;3;na;taylor3.png\n"
            + "52;The truck is towing a motorbike;Passive;1;left;truck_towing_motorbikeL.png\n"
            + "53;The man is painting;Filler;3;na;painter.png\n"
            + "54;The mother is dressing a boy;Passive;3;left;mother_dressing_boyL.png\n"
            + "55;The boy is surfing;Filler;3;na;surfer.png\n"
            + "56;Maid eating chocolate;Active;1;right;maid_eating_chocolate2R.png\n"
            + "57;The woman is calling;Filler;3;na;girlphone.png\n"
            + "58;The man is painting the door;Active;1;left;man_painting_door4L.png\n"
            + "59;The boy looks through a telescope;Filler;3;na;boy_telescope.png\n"
            + "60;The elephant is lifting a clown;Passive;3;left;elephant_lifting_clownL.png\n"
            + "61;The shoes are hanging in the tree;Filler;1;na;shoes_tree.png\n"
            + "62;The man is moving the armchair;Active;1;right;worker_moving_armchairR.png\n"
            + "63;The family is having a picknick;Filler;3;na;picnic.png\n"
            + "64;The thief is stealing the painting;Active;1;right;thief_stealing_painting3R.png\n"
            + "65;The girl is sitting under the table;Filler;3;na;girl_is_sitting_under_the_table_T.png\n"
            + "66;The train is crushing the bus;Passive;1;left;train_crushing_busL.png\n"
            + "67;The eagle sits on the tent;Filler;2;na;eagle_tent.png\n"
            + "68;The sprinkler is splashing the woman;Passive;3;right;sprinkler_splashing_womanR\n"
            + "69;The man is shaving;Filler;3;na;shaving.png\n"
            + "70;The cat scratched the sofa;Active;2;left;cat_ruining_sofaL.png\n"
            + "71;The man is sleeping under a tree;Filler;3;na;man_sleeping_under_tree_T.png\n"
            + "72;The crab cut the boy's foot;Passive;3;right;crab_cutting_boyR.png\n"
            + "73;The pot is boiling ;Filler;1;na;pot_boiling2.png\n"
            + "74;The man is carving a statue;Active;1;left;man_carving_statueL.png\n"
            + "75;Two goldfish swim in an aquarium;Filler;2;na;goldfish_two.png\n"
            + "76;The man is brushing the suit;Active;1;right;man_brushing_suitR.png\n"
            + "77;The woman is looking under the rug;Filler;1;na;woman_looking_under_rug.png\n"
            + "78;The lightning is striking a church;Passive;1;left;lightning_striking_church2L.png\n"
            + "79;The boy is sneezing;Filler;3;na;sneezing.png\n"
            + "80;The dog is catching the butterfly;Active;2;left;dog_catching_butterfly2L.png\n"
            + "81;The vase is falling off the table;Filler;1;na;vase.png\n"
            + "82;The photographer is filming a model;Passive;3;right;photographer_filming_modelR.png\n"
            + "83;The man is juggling;Filler;3;na;juggling.png\n"
            + "84;The fisherman caught the lobster;Active;2;right;fisherman_catching_lobsterR.png\n"
            + "85;The washing is hanging on the line;Filler;1;na;washing_on_the_line.png\n"
            + "86;The girl is pushing the boy on the sled;Passive;1;left;girl_pushing_boy2L.png\n"
            + "87;The woman is stretching;Filler;3;na;stretching2.png\n"
            + "88;The windmill blew away the farmer;Passive;3;left;windmill_hitting_farmer2L.png\n"
            + "89;The hen is sitting on her eggs;Filler;2;na;hen_sitting_on_eggs.png\n"
            + "90;The girl threw away the present;Active;1;right;girl_throwing_away_present3R.png\n"
            + "91;The old man is coughing;Filler;3;na;old_man_coughing.png\n"
            + "92;The bomb is hitting the ship;Passive;1;right;bomb_hitting_ship2R.png\n"
            + "93;The dolphin jumps through the hula hoop;Filler;2;na;dolphin2.png\n"
            + "94;The pirate is burying the treasure;Active;1;left;pirate_burying_treasureL.png\n"
            + "95;The man is lying in a hammock;Filler;3;na;hammock2.png\n"
            + "96;The boy is kicking the ball;Active;1;right;boy_kicking_ballR.png\n"
            + "97;The canoe is falling of the waterfall;Filler;1;na;canoe_waterfall.png\n"
            + "98;The barber is shaving the prisoner;Passive;3;right;barber_shaving_prisonerR.png\n"
            + "99;The woman walks out;Filler;3;na;woman_walking.png\n"
            + "100;The dog is chasing the mailman;Passive;3;left;dog_chasing_mailman2L.png\n"
            + "101;The leaves are falling from the tree;Filler;1;na;tree_leaves.png\n"
            + "102;The man is chopping a log;Active;1;right;man_chopping_log2R.png\n"
            + "103;The elephant is drinking water;Filler;2;na;elephant.png\n"
            + "104;the pope is crowning the king/prince;Passive;3;left;pope_crowning_princeL.png\n"
            + "105;The man and woman are walking under an umbrella;Filler;3;na;walking_umbrella.png\n"
            + "106;The little girl is pulling the suitcase;Active;1;left;girl_pulling_suitcaseL.png\n"
            + "107;The woman is playing the violin;Filler;3;na;practicing3.png\n"
            + "108;The army attacked the castle;Passive;1;right;army_attacking_castleR.png\n"
            + "109;The cat sits behind the chair;Filler;2;na;cathiding.png\n"
            + "110;the paparazzi is photographing the queen;Passive;3;right;paparazzi_photographing_queen2R.png\n"
            + "111;The ball falls down the hill;Filler;1;na;ball.png\n"
            + "112;The cat caught the mouse;Active;2;left;cat_catching_mouseL.png\n"
            + "113;The man is slipping;Filler;3;na;man_slipping2.png\n"
            + "114;The ambulance is hitting a woman;Passive;3;right;ambulance_hitting_woman2R.png\n"
            + "115;The hamster is running in a wheel;Filler;2;na;hamster.png\n"
            + "116;The girl is hanging the sheet;Active;1;right;girl_hanging_sheetR.png\n"
            + "117;The man climbs the mountain;Filler;3;na;climbing.png\n"
            + "118;The tiger scratched the tourist;Passive;3;left;tiger_scratching_tourist2L.png\n"
            + "119;The old man is reading (a book);Filler;3;na;grandfather.png\n"
            + "120;The eskimo_attacking_bear;Active;2;left;eskimo_attacking_bear2L.png";

}
