name: MVN Run Tests and Publish Artifacts
on:
  push:
    #branches-ignore:
    #  - '**' # disables this job
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: clean test deploy
      #run: mvn clean test -B -V -Duser.timezone=CET
      run: pwd;
            ls .;
            cd common;
            mvn clean test deploy -DaltDeploymentRepository=snapshot-repo::default::file:../../snapshots;
            cd ..;
            ls ../snapshots;
            ls ../snapshots/*;
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ../snapshots
